<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="teks"
    nsURI="http://teksme.org/meta/1.0.0/teks" nsPrefix="teks">
  <eClassifiers xsi:type="ecore:EClass" name="Teks">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="appId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="developer" eType="#//Developer"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="poll" eType="#//Poll" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="survey" eType="#//Survey"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responses" eType="#//Response"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outboundMessage" upperBound="-1"
        eType="#//OutboundTextMessage" containment="true" eOpposite="#//OutboundTextMessage/teksRef"
        eKeys="#//Message/id"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inboundMessage" upperBound="-1"
        eType="#//InboundTextMessage" containment="true" eKeys="#//Message/id"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="account" eType="#//User"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annotation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" upperBound="-1"
        eType="#//AnnotationMapEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationMapEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userName" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="country" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yearOfBirth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gender" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Developer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="websiteURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Poll">
    <eStructuralFeatures xsi:type="ecore:EReference" name="question" upperBound="-1"
        eType="#//PollQuestion" containment="true" eOpposite="#//PollQuestion/pollRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="settings" eType="#//PollSettings"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="replyMessage" eType="#//ReplyMessage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//Annotation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comments" upperBound="-1"
        eType="#//Comment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastModified" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Survey">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//Annotation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comments" upperBound="-1"
        eType="#//Comment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastModified" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PollSettings">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="closeDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scheduleStartDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="suspendOnFailure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" upperBound="-1"
        eType="#//LanguageKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="batchResponseDelivery"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="synchronousConfirmation"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="replyMessage" eType="#//ReplyMessage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="advertiseIt" eType="#//OutboundTextMessage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="folderID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sharing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responseRestrictions" eType="#//ResponseRestriction"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReplyMessage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="confirmation" upperBound="-1"
        eType="#//ReplyMessage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultMessage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customMessage" eType="#//OutboundTextMessage"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Response">
    <eStructuralFeatures xsi:type="ecore:EReference" name="response" upperBound="-1"
        eType="#//ResponseDetail" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseRestriction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acceptMultipleChannels"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="communicationChannel" upperBound="-1"
        eType="#//ChannelKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="restrictionType" eType="#//RestrictionKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockRepeat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="moderateFirst" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PollQuestion" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pollRef" eType="#//Poll"
        eOpposite="#//Poll/question"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlainText" abstract="true" eSuperTypes="#//PollQuestion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="question" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyword" eType="#//Keyword"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Keyword">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoKeyword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FreeText" eSuperTypes="#//PlainText"/>
  <eClassifiers xsi:type="ecore:EClass" name="SecureText" eSuperTypes="#//PlainText">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hashAlgorithm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hashEncoding" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultipleChoice" eSuperTypes="#//PollQuestion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="question" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="answer" upperBound="-1"
        eType="#//Answer" containment="true" eOpposite="#//Answer/questionRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="addOther" eType="#//FreeText"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Answer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyword" eType="#//Keyword"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="questionRef" eType="#//MultipleChoice"
        eOpposite="#//MultipleChoice/answer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseDetail">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rawMessage" eType="#//InboundTextMessage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="setValue" upperBound="-1"
        eType="#//AnswerRef" containment="true" eKeys="#//AnswerRef/id"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="communicationChannel" upperBound="-1"
        eType="#//ChannelKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="smsGateway" eType="#//SMSGatewayKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectMessage" eSuperTypes="#//Message"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnswerRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="choiceRef" eType="#//PollQuestion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="answerRef" eType="#//Answer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InboundTextMessage" eSuperTypes="#//Message">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="partNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="originator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="smscNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" eType="#//TextMessage"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutboundTextMessage" eSuperTypes="#//Message">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="retryCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refNo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teksRef" eType="#//Teks"
        eOpposite="#//Teks/outboundMessage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recipient" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="from" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deliveryDelayTime" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validityTimeframe" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clientMsgId" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deliveryQueuePriority"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deliveryAck" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="callbackCode" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="concatenated" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageStatus" upperBound="-1"
        eType="#//MessageStatuses"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mobileOriginated" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="failureCause" upperBound="-1"
        eType="#//FailureCauses"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encoding" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deliveryScheduledTime"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" eType="#//TextMessage"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextMessage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Report">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hideResults" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentageOnly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultHandler" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LanguageKind">
    <eLiterals name="en_US" literal="English"/>
    <eLiterals name="pt_BR" value="1" literal="Portuguese"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ChannelKind">
    <eLiterals name="SMS"/>
    <eLiterals name="EMAIL" value="1" literal="Email"/>
    <eLiterals name="WEB" value="2" literal="Web"/>
    <eLiterals name="TWITTER" value="3" literal="Twitter"/>
    <eLiterals name="WEB_WIDGET" value="4" literal="Web Widget"/>
    <eLiterals name="IVR" value="5"/>
    <eLiterals name="MMS" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RestrictionKind">
    <eLiterals name="EVERYONE" literal="Everyone"/>
    <eLiterals name="RIGESTERED_USER" value="1" literal="Participants Only"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StopCommandKind">
    <eLiterals name="STOP"/>
    <eLiterals name="END" value="1"/>
    <eLiterals name="CANCEL" value="2"/>
    <eLiterals name="UNSUBSCRIBE" value="3"/>
    <eLiterals name="QUIT" value="4"/>
    <eLiterals name="STOP_STOP" value="5" literal="STOP STOP"/>
    <eLiterals name="STOP_ALL" value="6" literal="STOP ALL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MessageStatuses">
    <eLiterals name="MSG_UNKNOWN" value="1"/>
    <eLiterals name="MSG_QUEUED" value="2"/>
    <eLiterals name="DELIVERED_GATEWAY" value="3" literal="DELIVERED_GATEWAY"/>
    <eLiterals name="RECEIVED_BY_RECIPIENT" value="4"/>
    <eLiterals name="ERROR_WITH_MSG" value="5"/>
    <eLiterals name="USER_CANCELLED_MSG" value="6"/>
    <eLiterals name="ERROR_DELIVERING_MSG" value="7"/>
    <eLiterals name="SENT" value="8"/>
    <eLiterals name="ROUTING_ERROR" value="9"/>
    <eLiterals name="MSG_EXPIRED" value="10"/>
    <eLiterals name="MSG_QUEUED_FOR_LATER_DELIVERY" value="11"/>
    <eLiterals name="UNSENT" value="12" literal="UNSENT"/>
    <eLiterals name="FAILED" value="13"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FailureCauses">
    <eLiterals name="NO_ERROR"/>
    <eLiterals name="BAD_NUMBER" value="1"/>
    <eLiterals name="BAD_FORMAT" value="2"/>
    <eLiterals name="GATEWAY_FAILURE" value="3"/>
    <eLiterals name="NO_CREDIT" value="4"/>
    <eLiterals name="GATEWAY_AUTH" value="5"/>
    <eLiterals name="NO_ROUTE" value="6"/>
    <eLiterals name="UNKNOWN" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SMSGatewayKind">
    <eLiterals name="CLICKATELL"/>
    <eLiterals name="DIGICEL" value="1"/>
    <eLiterals name="MOVISTAR_PERU" value="2"/>
    <eLiterals name="MODEM" value="3"/>
  </eClassifiers>
</ecore:EPackage>
