var STRING_TABLE = {
	"INTERFACE_CONTINUE_TO_TASKS" : "Continue to Tasks",
	"INTERFACE_ALWAYS_SKIP_THIS_PAGE" : "Always skip this page",
	"INTERFACE_WHATS_NEW" : "What's New?",
	"INTERFACE_SHARED_TASKS" : "shared tasks",
	"INTERFACE_EMAILED_TASKS" : "emailed tasks",
	"INTERFACE_SHARED_LISTS" : "shared lists",
	"INTERFACE_WHAT_IS_THIS" : "What is this?",
	"INTERFACE_SHOW_SEARCH_OPTIONS" : "Show search options",
	"INTERFACE_HIDE_SEARCH_OPTIONS" : "Hide search options",
	"INTERFACE_WEEKLY_PLANNER" : "Weekly Planner",
	"INTERFACE_PRINT_WEEKLY_PLANNER" : "Print Weekly Planner",
	"INTERFACE_OVERVIEW_TODAY" : "Today",
	"INTERFACE_OVERVIEW_TOMORROW" : "Tomorrow",
	"INTERFACE_OVERVIEW_OVERDUE" : "Overdue",
	"INTERFACE_DONT_SKIP_THIS_PAGE" : "Don't skip this page",
	"INTERFACE_NAV_ABOUT" : "About",
	"INTERFACE_NAV_BLOG" : "Blog",
	"INTERFACE_NAV_FORUMS" : "Forums",
	"INTERFACE_NAV_TERMS_OF_USE" : "Terms of Use",
	"INTERFACE_NAV_PRIVACY_POLICY" : "Privacy Policy",
	"INTERFACE_NAV_FEEDBACK" : "Feedback",
	"INTERFACE_SEARCH_SEARCH" : "Search",
	"INTERFACE_SEARCH_ALL_LISTS" : "All lists",
	"INTERFACE_SEARCH_PRIORITY" : "Priority",
	"INTERFACE_SEARCH_PRIORITY_ANY" : "Any",
	"INTERFACE_SEARCH_STATUS" : "Status",
	"INTERFACE_SEARCH_STATUS_ANY" : "Any",
	"INTERFACE_SEARCH_PRIORITY_1" : "Priority 1",
	"INTERFACE_SEARCH_PRIORITY_2" : "Priority 2",
	"INTERFACE_SEARCH_PRIORITY_3" : "Priority 3",
	"INTERFACE_SEARCH_PRIORITY_NONE" : "No Priority",
	"INTERFACE_SEARCH_STATUS_INCOMPLETE" : "Incomplete",
	"INTERFACE_SEARCH_STATUS_COMPLETED" : "Completed",
	"INTERFACE_SEARCH_SHARED_WITH" : "Shared with",
	"INTERFACE_SEARCH_SHARED_WITH_DOESNT_MATTER" : "Doesn't matter",
	"INTERFACE_SEARCH_SHARED_WITH_NO_ONE" : "No one",
	"INTERFACE_SEARCH_SHARED_WITH_SOMEONE" : "Someone",
	"INTERFACE_SEARCH_TAGGED_WITH" : "Tagged with",
	"INTERFACE_SEARCH_HAS_THE_WORDS" : "Has the words",
	"INTERFACE_SEARCH_DOESNT_HAVE" : "Doesn't have",
	"INTERFACE_SEARCH_NOTES" : "Search notes?",
	"INTERFACE_SEARCH_INCLUDE_ARCHIVED" : "Include archived?",
	"INTERFACE_SEARCH_DUE_DATE_WITHIN" : "Due date within {DURATION} of {DATE}",
	"INTERFACE_SEARCH_TASKS" : "Search Tasks",
	"INTERFACE_SEARCH_CANCEL" : "Cancel",
	"INTERFACE_TOP_NAV_OVERVIEW" : "Overview",
	"INTERFACE_TOP_NAV_TASKS" : "Tasks",
	"INTERFACE_TOP_NAV_CONTACTS" : "Contacts",
	"INTERFACE_TOP_NAV_SETTINGS" : "Settings",
	"INTERFACE_TOP_NAV_HELP" : "Help",
	"INTERFACE_TOP_NAV_LOGOUT" : "Logout",
	"INTERFACE_TASKS_BUTTON_COMPLETE" : "Complete",
	"INTERFACE_TASKS_BUTTON_POSTPONE" : "Postpone",
	"INTERFACE_TASKS_BUTTON_UNCOMPLETE" : "Uncomplete",
	"INTERFACE_TASKS_TOOLBOX_MORE_ACTIONS" : "More Actions...",
	"INTERFACE_TASKS_TOOLBOX_PRIORITIZE" : "Prioritize...",
	"INTERFACE_TASKS_TOOLBOX_SET_PRIORITY_1" : "Set Priority 1",
	"INTERFACE_TASKS_TOOLBOX_SET_PRIORITY_2" : "Set Priority 2",
	"INTERFACE_TASKS_TOOLBOX_SET_PRIORITY_3" : "Set Priority 3",
	"INTERFACE_TASKS_TOOLBOX_SET_PRIORITY_NONE" : "Set No Priority",
	"INTERFACE_TASKS_TOOLBOX_MOVE_PRIORITY_UP" : "Move Priority Up",
	"INTERFACE_TASKS_TOOLBOX_MOVE_PRIORITY_DOWN" : "Move Priority Down",
	"INTERFACE_TASKS_TOOLBOX_MOVE_TO" : "Move To...",
	"INTERFACE_TASKS_TOOLBOX_MOVE_TO_LIST" : "\"{LIST_NAME}\" list",
	"INTERFACE_TASKS_TOOLBOX_SEND_TO" : "Send To...",
	"INTERFACE_TASKS_TOOLBOX_SHARE_WITH" : "Share With...",
	"INTERFACE_TASKS_TOOLBOX_UNDO_LAST_ACTION" : "Undo Last Action",
	"INTERFACE_TASKS_TOOLBOX_DELETE_TASK" : "Delete Task",
	"INTERFACE_TASKS_SELECT" : "Select:",
	"INTERFACE_TASKS_SELECT_ALL" : "All",
	"INTERFACE_TASKS_SELECT_DUE_TODAY" : "Due Today",
	"INTERFACE_TASKS_SELECT_DUE_TOMORROW" : "Due Tomorrow",
	"INTERFACE_TASKS_SELECT_OVERDUE" : "Overdue",
	"INTERFACE_TASKS_SELECT_NONE" : "None",
	"INTERFACE_TASKS_LIST_DETAILS_ZERO_TASKS" : "0 tasks",
	"INTERFACE_TASKS_LIST_DETAILS_ONE_TASK" : "1 task",
	"INTERFACE_TASKS_LIST_DETAILS_NUM_TASKS" : "{NUM} tasks",
	"INTERFACE_TASKS_LIST_DETAILS_ZERO_DUE_TODAY" : "0 due today",
	"INTERFACE_TASKS_LIST_DETAILS_NUM_DUE_TODAY" : "{NUM} due today",
	"INTERFACE_TASKS_LIST_DETAILS_ZERO_DUE_TOMORROW" : "0 due tomorrow",
	"INTERFACE_TASKS_LIST_DETAILS_NUM_DUE_TOMORROW" : "{NUM} due tomorrow",
	"INTERFACE_TASKS_LIST_DETAILS_ZERO_OVERDUE" : "0 overdue",
	"INTERFACE_TASKS_LIST_DETAILS_NUM_OVERDUE" : "{NUM} overdue",
	"INTERFACE_TASKS_LIST_DETAILS_ZERO_COMPLETED" : "0 completed",
	"INTERFACE_TASKS_LIST_DETAILS_NUM_COMPLETED" : "{NUM} completed",
	"INTERFACE_TASKS_LIST_DETAILS_ZERO_INCOMPLETE" : "0 incomplete",
	"INTERFACE_TASKS_LIST_DETAILS_NUM_INCOMPLETE" : "{NUM} incomplete",
	"INTERFACE_TASKS_LIST_DETAILS_PRINT" : "Print",
	"INTERFACE_TASKS_LIST_DETAILS_ICALENDAR" : "iCalendar",
	"INTERFACE_TASKS_LIST_DETAILS_ICALENDAR_EVENTS" : "iCalendar (Events)",
	"INTERFACE_TASKS_LIST_DETAILS_ATOM" : "Atom",
	"INTERFACE_TASKS_LIST_DETAILS_LIST" : "List",
	"INTERFACE_TASKS_LIST_DETAILS_SHARE" : "Share",
	"INTERFACE_TASKS_LIST_DETAILS_PUBLISH" : "Publish",
	"INTERFACE_TASKS_LIST_DETAILS_SHARE_NOT_SHARED" : "Not shared",
	"INTERFACE_TASKS_LIST_DETAILS_SHARE_SHARED_WITH_CONTACTS" : "Shared with contacts",
	"INTERFACE_TASKS_LIST_DETAILS_SHARE_DO_NOT_SHARE_LIST" : "Do not share list",
	"INTERFACE_TASKS_LIST_DETAILS_SHARE_SHARE_WITH_CONTACTS" : "Share with contact(s)",
	"INTERFACE_TASKS_LIST_DETAILS_SHARE_DONT_SHARE" : "Don't share",
	"INTERFACE_TASKS_LIST_DETAILS_SHARE_SHARE_WITH_CONTACTS_BUTTON" : "Share with contacts...",
	"INTERFACE_TASKS_LIST_DETAILS_SHARE_SHARE_WITH_MORE_BUTTON" : "Share with more...",
	"INTERFACE_TASKS_LIST_DETAILS_SHARE_GROUP" : "(Group)",
	"INTERFACE_TASKS_LIST_DETAILS_SHARE_PENDING" : "(Pending)",
	"INTERFACE_TASKS_LIST_DETAILS_PUBLISH_NOT_PUBLISHED" : "Not published",
	"INTERFACE_TASKS_LIST_DETAILS_PUBLISH_PUBLISHED_TO_CONTACTS" : "Published to contacts",
	"INTERFACE_TASKS_LIST_DETAILS_PUBLISH_PUBLIC_LIST" : "Public list",
	"INTERFACE_TASKS_LIST_DETAILS_PUBLISH_DO_NOT_PUBLISH" : "Do not publish",
	"INTERFACE_TASKS_LIST_DETAILS_PUBLISH_PUBLISH_FOR_CONTACTS" : "Publish for contact(s)",
	"INTERFACE_TASKS_LIST_DETAILS_PUBLISH_MAKE_THIS_LIST_PUBLIC" : "Make this list public",
	"INTERFACE_TASKS_LIST_DETAILS_PUBLISH_DONT_PUBLISH_BUTTON" : "Don't publish",
	"INTERFACE_TASKS_LIST_DETAILS_PUBLISH_PUBLISH_FOR_CONTACTS_BUTTON" : "Publish for contacts...",
	"INTERFACE_TASKS_LIST_DETAILS_PUBLISH_PUBLISH_FOR_MORE_BUTTON" : "Publish for more...",
	"INTERFACE_TASKS_LIST_DETAILS_PUBLISH_PUBLISH_BUTTON" : "Publish",
	"INTERFACE_TASKS_LIST_DETAILS_PUBLISH_LINK" : "Link to this published list",
	"INTERFACE_TASKS_LIST_DETAILS_PERMALINK" : "Permalink",
	"INTERFACE_TASKS_LIST_DETAILS_LOADING" : "Loading...",
	"INTERFACE_TASKS_LIST_DETAILS_SEARCHED_FOR" : "Searched for: {CRITERIA}",
	"INTERFACE_TASKS_LIST_DETAILS_SEARCH_RESULTS" : "Search Results",
	"INTERFACE_TASKS_LIST_DETAILS_TIME_ESTIMATE_ONE_MINUTE" : "1 minute",
	"INTERFACE_TASKS_LIST_DETAILS_TIME_ESTIMATE_NUM_MINUTES" : "{NUM} minutes",
	"INTERFACE_TASKS_LIST_DETAILS_TIME_ESTIMATE_ONE_DAY" : "1 day",
	"INTERFACE_TASKS_LIST_DETAILS_TIME_ESTIMATE_NUM_DAYS" : "{NUM} days",
	"INTERFACE_TASKS_LIST_DETAILS_TIME_ESTIMATE_ONE_HOUR" : "1 hour",
	"INTERFACE_TASKS_LIST_DETAILS_TIME_ESTIMATE_NUM_HOURS" : "{NUM} hours",
	"INTERFACE_TASKS_LIST_DETAILS_TIME_ESTIMATE" : "{TIME} estimated",
	"INTERFACE_TASKS_ADD_TASK" : "Add Task",
	"INTERFACE_TASKS_TOOLTOP_ADD" : "Add {KEY}",
	"INTERFACE_TASKS_TASK_DETAILS_LIST" : "List",
	"INTERFACE_TASKS_TASK_DETAILS_DUE" : "Due",
	"INTERFACE_TASKS_TASK_DETAILS_REPEAT" : "Repeat",
	"INTERFACE_TASKS_TASK_DETAILS_TIME_ESTIMATE" : "Time estimate",
	"INTERFACE_TASKS_TASK_DETAILS_TAGS" : "Tags",
	"INTERFACE_TASKS_TASK_DETAILS_POSTPONED" : "Postponed",
	"INTERFACE_TASKS_TASK_DETAILS_SENT_FROM" : "Sent from",
	"INTERFACE_TASKS_TASK_DETAILS_SHARED_WITH" : "Shared with",
	"INTERFACE_TASKS_TASK_DETAILS_NOTES" : "Notes",
	"INTERFACE_TASKS_TASK_DETAILS_DUE_NEVER" : "never",
	"INTERFACE_TASKS_TASK_DETAILS_REPEAT_NEVER" : "never",
	"INTERFACE_TASKS_TASK_DETAILS_TIME_ESTIMATE_NONE" : "none",
	"INTERFACE_TASKS_TASK_DETAILS_TAGS_NONE" : "none",
	"INTERFACE_TASKS_TASK_DETAILS_POSTPONED_ZERO" : "0 times",
	"INTERFACE_TASKS_TASK_DETAILS_POSTPONED_ONE" : "1 time",
	"INTERFACE_TASKS_TASK_DETAILS_POSTPONED_NUM" : "{NUM} times",
	"INTERFACE_TASKS_TASK_DETAILS_SENT_FROM_EMAILED" : "Emailed in",
	"INTERFACE_TASKS_TASK_DETAILS_SHARED_WITH_NO_ONE" : "no one",
	"INTERFACE_TASKS_TASK_DETAILS_TASK_TAB" : "Task",
	"INTERFACE_TASKS_TASK_DETAILS_NOTES_TAB" : "Notes",
	"INTERFACE_TASKS_SELECTED_ONE_TASK" : "1 task selected.",
	"INTERFACE_TASKS_SELECTED_NUM_TASKS" : "{NUM} tasks selected.",
	"INTERFACE_TASKS_SELECTED_ONE_TASK_MULTIEDIT" : "1 task selected (multi-edit).",
	"INTERFACE_TASKS_SELECTED_NUM_TASKS_MULTIEDIT" : "{NUM} tasks selected (multi-edit).",
	"INTERFACE_TASKS_SAVE_TAB" : "Save",
	"INTERFACE_TASKS_SAVE_SMART_LIST_AS" : "Save Smart List as:",
	"INTERFACE_TASKS_SAVE_BUTTON" : "Save",
	"INTERFACE_TASKS_SEARCH_TAB" : "Search",
	"INTERFACE_CONTACTS_CONTACTS_TAB" : "Contacts",
	"INTERFACE_CONTACTS_GROUPS_TAB" : "Groups",
	"INTERFACE_CONTACTS_INVITES_TAB" : "Invites",
	"INTERFACE_CONTACTS_CONTACTS_DELETE_BUTTON" : "Delete",
	"INTERFACE_CONTACTS_CONTACTS_TOOLBOX_MORE_ACTIONS" : "More Actions...",
	"INTERFACE_CONTACTS_CONTACTS_TOOLBOX_ADD_TO" : "Add To...",
	"INTERFACE_CONTACTS_CONTACTS_TOOLBOX_REMOVE_FROM" : "Remove From...",
	"INTERFACE_CONTACTS_CONTACTS_TOOLBOX_GROUP" : "\"{GROUP_NAME}\" group",
	"INTERFACE_CONTACTS_CONTACT_TAB" : "Contact",
	"INTERFACE_CONTACTS_CONTACTS_ZERO" : "0 contacts",
	"INTERFACE_CONTACTS_CONTACTS_ONE" : "1 contact",
	"INTERFACE_CONTACTS_CONTACTS_NUM" : "{NUM} contacts",
	"INTERFACE_CONTACTS_ADD_CONTACT" : "Add Contact",
	"INTERFACE_CONTACTS_CONTACT_USERNAME" : "Username",
	"INTERFACE_CONTACTS_CONTACT_GROUPS" : "In groups",
	"INTERFACE_CONTACTS_CONTACT_VIEW_TASKS_SHARED" : "View tasks shared with {CONTACT_FIRST_NAME}",
	"INTERFACE_CONTACTS_CONTACT_GROUPS_NONE" : "none",
	"INTERFACE_CONTACTS_SELECTED_ONE" : "1 contact selected.",
	"INTERFACE_CONTACTS_SELECTED_NUM" : "{NUM} contacts selected.",
	"INTERFACE_CONTACTS_GROUPS_DELETE_BUTTON" : "Delete",
	"INTERFACE_CONTACTS_GROUPS_GROUP_TAB" : "Group",
	"INTERFACE_CONTACTS_GROUPS_ZERO" : "0 groups",
	"INTERFACE_CONTACTS_GROUPS_ONE" : "1 group",
	"INTERFACE_CONTACTS_GROUPS_NUM" : "{NUM} groups",
	"INTERFACE_CONTACTS_GROUPS_ADD_GROUP" : "Add Group",
	"INTERFACE_CONTACTS_GROUPS_MEMBERS_ZERO" : "0 members",
	"INTERFACE_CONTACTS_GROUPS_MEMBERS_ONE" : "1 member",
	"INTERFACE_CONTACTS_GROUPS_MEMBERS_NUM" : "{NUM} members",
	"INTERFACE_CONTACTS_GROUPS_MEMBERS" : "Members",
	"INTERFACE_CONTACTS_GROUPS_SELECTED_ONE" : "1 group selected.",
	"INTERFACE_CONTACTS_GROUPS_SELECTED_NUM" : "{NUM} groups selected.",
	"INTERFACE_CONTACTS_GROUPS_MEMBERS_NONE" : "none",
	"INTERFACE_CONTACTS_INVITES_SEND_TO" : "Send an invite to...",
	"INTERFACE_CONTACTS_INVITES_FIRST_NAME" : "First Name   \t  ",
	"INTERFACE_CONTACTS_INVITES_EMAIL" : "Email",
	"INTERFACE_CONTACTS_INVITES_NOTE" : "Note",
	"INTERFACE_CONTACTS_INVITES_SEND" : "Send Invite",
	"INTERFACE_SETTINGS_GENERAL_TAB" : "General",
	"INTERFACE_SETTINGS_LISTS_TAB" : "Lists",
	"INTERFACE_SETTINGS_REMINDERS_TAB" : "Reminders",
	"INTERFACE_SETTINGS_SERVICES_TAB" : "Services",
	"INTERFACE_SETTINGS_INFO_TAB" : "Info",
	"INTERFACE_SETTINGS_GENERAL_DESCRIPTION" : "General Settings",
	"INTERFACE_SETTINGS_GENERAL_FIRST_NAME" : "First Name",
	"INTERFACE_SETTINGS_GENERAL_LAST_NAME" : "Last Name",
	"INTERFACE_SETTINGS_GENERAL_PASSWORD" : "Password",
	"INTERFACE_SETTINGS_GENERAL_PASSWORD_CHANGE" : "Change your password",
	"INTERFACE_SETTINGS_GENERAL_EMAIL" : "Email Address",
	"INTERFACE_SETTINGS_GENERAL_DATE_FORMAT" : "Which Looks Right",
	"INTERFACE_SETTINGS_GENERAL_TIME_FORMAT" : "Time Format",
	"INTERFACE_SETTINGS_GENERAL_COUNTRY" : "Country",
	"INTERFACE_SETTINGS_GENERAL_TIMEZONE" : "Timezone",
	"INTERFACE_SETTINGS_GENERAL_SAVE_CHANGES" : "Save Changes",
	"INTERFACE_SETTINGS_GENERAL_CANCEL" : "Cancel",
	"INTERFACE_SETTINGS_LISTS_ARCHIVE_BUTTON" : "Archive",
	"INTERFACE_SETTINGS_LISTS_TOOLBOX_MORE_ACTIONS" : "More Actions...",
	"INTERFACE_SETTINGS_LISTS_TOOLBOX_SET_AS_DEFAULT" : "Set As Default",
	"INTERFACE_SETTINGS_LISTS_TOOLBOX_UNSET_AS_DEFAULT" : "Unset As Default",
	"INTERFACE_SETTINGS_LISTS_TOOLBOX_ARCHIVE_LIST" : "Archive List",
	"INTERFACE_SETTINGS_LISTS_TOOLBOX_UNARCHIVE_LIST" : "Unarchive List",
	"INTERFACE_SETTINGS_LISTS_TOOLBOX_DELETE_LIST" : "Delete List",
	"INTERFACE_SETTINGS_LISTS_NUM_LISTS" : "{NUM} lists",
	"INTERFACE_SETTINGS_LISTS_ADD_LIST" : "Add List",
	"INTERFACE_SETTINGS_LISTS_LIST_LOCKED" : "This list is locked. It cannot be modified or deleted.",
	"INTERFACE_SETTINGS_LISTS_SMART_LIST" : "This is a Smart List.",
	"INTERFACE_SETTINGS_LISTS_CRITERIA" : "It shows tasks matching: {CRITERIA}",
	"INTERFACE_SETTINGS_LISTS_ARCHIVED" : "This list is archived. {START_LINK}Unarchive?{END_LINK}",
	"INTERFACE_SETTINGS_LISTS_SELECTED_ONE" : "1 list selected.",
	"INTERFACE_SETTINGS_LISTS_SELECTED_NUM" : "{NUM} lists selected.",
	"INTERFACE_SETTINGS_REMINDERS_DESCRIPTION" : "Reminder Settings",
	"INTERFACE_SETTINGS_REMINDERS_DAILY_REMINDERS_LABEL" : "Send me a daily reminder...",
	"INTERFACE_SETTINGS_REMINDERS_ON_THE_DAY" : "On the day the task is due",
	"INTERFACE_SETTINGS_REMINDERS_X_BEFORE_THE_TASK_IS_DUE" : "{FIELD} before the task is due",
	"INTERFACE_SETTINGS_REMINDERS_SEND_DAILY_REMINDERS_AT" : "Send daily reminders at {FIELD}",
	"INTERFACE_SETTINGS_REMINDERS_IF_THE_TASK_HAS_A_DUE_TIME" : "If the task has a due time, remind me...",
	"INTERFACE_SETTINGS_REMINDERS_AT_THE_TIME" : "At the time the task is due",
	"INTERFACE_SETTINGS_REMINDERS_X_BEFORE_THE_TASK_TIME_DUE" : "{FIELD} before the task is due",
	"INTERFACE_SETTINGS_REMINDERS_SAVE_CHANGES" : "Save Changes",
	"INTERFACE_SETTINGS_REMINDERS_CANCEL" : "Cancel",
	"INTERFACE_SETTINGS_REMINDERS_I_WANT_TO_BE" : "I want to be reminded by...",
	"INTERFACE_SETTINGS_REMINDERS_ADD_DETAILS" : "Add Details",
	"INTERFACE_SETTINGS_REMINDERS_EMAIL" : "Email",
	"INTERFACE_SETTINGS_REMINDERS_MOBILE" : "Mobile",
	"INTERFACE_SETTINGS_REMINDERS_DELETE_DETAILS" : "Delete Details",
	"INTERFACE_SETTINGS_REMINDERS_SELECT_YOUR_NETWORK" : "Select your network",
	"INTERFACE_SETTINGS_REMINDERS_MOBILE_OTHER" : "Other",
	"INTERFACE_SETTINGS_REMINDERS_DAILY_MESSAGE_LIMIT" : "{FIELD} daily message limit",
	"INTERFACE_SETTINGS_REMINDERS_MOBILE_UNLIMITED" : "unlimited",
	"INTERFACE_SETTINGS_SERVICES_SERVICE" : "Service",
	"INTERFACE_SETTINGS_SERVICES_VIEW" : "View?",
	"INTERFACE_SETTINGS_SERVICES_MODIFY" : "Modify?",
	"INTERFACE_SETTINGS_SERVICES_DELETE" : "Delete?",
	"INTERFACE_SETTINGS_SERVICES_REMOVE" : "Remove Permissions",
	"INTERFACE_SETTINGS_INFO_DESCRIPTION" : "Account Information",
	"INTERFACE_SETTINGS_INFO_USERNAME" : "Username",
	"INTERFACE_SETTINGS_INFO_INBOX" : "Inbox Email Address",
	"INTERFACE_SETTINGS_INFO_IMPORT" : "Import Email Address",
	"INTERFACE_SETTINGS_INFO_ICALENDAR" : "iCalendar Service (All Lists)",
	"INTERFACE_SETTINGS_INFO_ICALENDAR_EVENTS" : "iCalendar Events Service (All Lists)",
	"INTERFACE_SETTINGS_INFO_ATOM" : "Atom Feed (All Lists)",
	"INTERFACE_SETTINGS_INFO_PUBLIC_LISTS" : "Public Lists",
	"INTERFACE_ERROR_CONTACTS_ADD_ALREADYEXISTS" : "Sorry, I can't add that contact since they are already in your list.",
	"INTERFACE_ERROR_CONTACTS_ADD_FAILURE" : "There was a problem adding the contact. Please try again.",
	"INTERFACE_ERROR_CONTACTS_ADD_EMAILSPECIFIED" : "That person doesn't appear to be a {RTM} member. {START_LINK}Would you like to invite them?{END_LINK}",
	"INTERFACE_ERROR_CONTACTS_ADD_NOYOURSELF" : "Sorry, you can't add yourself as a contact...",
	"INTERFACE_ERROR_CONTACTS_ADD_NOEXIST" : "That person doesn't appear to be a {RTM} member.",
	"INTERFACE_ERROR_GROUPS_ADD_FAILURE" : "There was a problem adding the group. Please try again.",
	"INTERFACE_ERROR_GROUPS_ADD_ALREADYEXISTS" : "Sorry, I can't add that group since it is already in your list.",
	"INTERFACE_HELP_LISTS_REMOVING" : "{START_BOLD}Note:{END_BOLD} Removing a list will not delete the tasks within that list. Any tasks will be moved to your Inbox.",
	"INTERFACE_HELP_TASKS_DUEDATE" : "Enter a due date such as {START_ITALIC}Aug 5{END_ITALIC}, {START_ITALIC}Tomorrow{END_ITALIC}, or {START_ITALIC}Next Tuesday{END_ITALIC}. {START_LINK}Learn more{END_LINK} about due dates.",
	"INTERFACE_HELP_TASKS_REOCCUR" : "Enter how often the task repeats, e.g. {START_ITALIC}Every Week{END_ITALIC} or {START_ITALIC}After 14 days{END_ITALIC}. {START_LINK}Learn more{END_LINK} about repeating tasks.",
	"INTERFACE_HELP_TASKS_DURATION" : "Enter a time estimate for the task, e.g. {START_ITALIC}30 minutes{END_ITALIC} or {START_ITALIC}2 hours{END_ITALIC}. {START_LINK}Learn more{END_LINK} about time estimates.",
	"INTERFACE_HELP_TASKS_TAGS" : "Enter tags such as {START_ITALIC}bill{END_ITALIC} or {START_ITALIC}supermarket{END_ITALIC} separated by spaces. Join two words together by using double quotes: {START_ITALIC}\"work meeting\"{END_ITALIC}. {START_LINK}Learn more{END_LINK} about tags.",
	"INTERFACE_HELP_TASKS_INBOX" : "The {START_ITALIC}Inbox{END_ITALIC} is just like your email inbox - except that instead of emails, you'll receive tasks. {START_LINK}Learn more{END_LINK} about the Inbox.",
	"INTERFACE_HELP_TASKS_SENT" : "The {START_ITALIC}Sent{END_ITALIC} list stores the tasks that you've sent to other users. {START_LINK}Learn more{END_LINK} about the Sent list.",
	"INTERFACE_HELP_TASKS_PUBLISHING" : "{START_ITALIC}Publishing{END_ITALIC} allows others to see, but not change, the contents of your list. {START_LINK}Learn more{END_LINK} about publishing.",
	"INTERFACE_HELP_TASKS_SHARING" : "{START_ITALIC}Sharing{END_ITALIC} allows others to both see and change the contents of your list. {START_LINK}Learn more{END_LINK} about sharing.",
	"INTERFACE_HELP_TASKS_SAVE" : "{START_ITALIC}Smart Lists{END_ITALIC} are created based on your search criteria, and are automatically updated as your tasks change. {START_LINK}Learn more{END_LINK} about Smart Lists.",
	"INTERFACE_HELP_CONTACTS" : "{START_ITALIC}Contacts{END_ITALIC} are other users who you can share with or send tasks to. {START_LINK}Learn more{END_LINK} about contacts.",
	"INTERFACE_HELP_CONTACTS_ADD" : "Enter a username or email address to add a contact.",
	"INTERFACE_HELP_GROUPS" : "{START_ITALIC}Groups{END_ITALIC} are groupings of your contacts. Give them names like {START_ITALIC}Friends{END_ITALIC} or {START_ITALIC}Colleagues{END_ITALIC}. {START_LINK}Learn more{END_LINK} about groups.",
	"INTERFACE_HELP_INVITES" : "Do you love {RTM}? We hope so...\r\n\r\nLet your friends know that {RTM} exists by typing in their first name, email address and possibly attaching a note that rants and raves about just how cool this really is.",
	"INTERFACE_HELP_REMINDERS_DATEDUE" : "Tell us how long before the task is due you want to be reminded, e.g. {START_ITALIC}1 day{END_ITALIC} or {START_ITALIC}2 weeks{END_ITALIC}. {START_LINK}Learn more{END_LINK} about reminders.",
	"INTERFACE_HELP_REMINDERS_START" : "Tell us what time you'd like to receive daily reminders, e.g. {START_ITALIC}12am{END_ITALIC} or {START_ITALIC}9am{END_ITALIC}. {START_LINK}Learn more{END_LINK} about reminders.",
	"INTERFACE_HELP_REMINDERS_TIMEDUE" : "Tell us how long before the task is due you want to be reminded (if the task has a due time), e.g. {START_ITALIC}10 minutes{END_ITALIC} or {START_ITALIC}1 hour{END_ITALIC}. {START_LINK}Learn more{END_LINK} about reminders.",
	"INTERFACE_HELP_REMINDERS_EMAIL" : "Enter the email address where reminders should be sent.",
	"INTERFACE_HELP_REMINDERS_IM" : "Enter your instant messenger username or email address.",
	"INTERFACE_HELP_REMINDERS_PHONE" : "Enter the phone number where reminders should be sent.",
	"INTERFACE_HELP_REMINDERS_OTHER" : "Enter your phone's email address where reminders should be sent. {START_LINK}Learn more{END_LINK} about setting reminders.",
	"INTERFACE_HELP_REMINDERS_NETWORK" : "{START_BOLD}Note:{END_BOLD} Your network may charge you to receive text messages; you may wish to check with them before using this service.",
	"INTERFACE_HELP_REMINDERS_SMSMAX" : "Enter the maximum number of reminders you wish to receive each day (or {START_ITALIC}unlimited{END_ITALIC}).",
	"INTERFACE_HELP_SETTINGS_GENERAL" : "Want to change your name? Email address? Password? Timezone? It's all here.",
	"INTERFACE_HELP_SETTINGS_LISTS" : "Manage your lists. You can have as many as you like (yes, really).",
	"INTERFACE_HELP_SETTINGS_REMINDERS" : "Set reminders to be reminded whenever and however you like - email, instant messenger, or SMS.",
	"INTERFACE_HELP_SETTINGS_SERVICES" : "Any {START_LINK}third-party services{END_LINK} that you have given permission to interact with your {RTM} account are listed here.",
	"INTERFACE_HELP_SETTINGS_INFO" : "These are useful account details. {START_LINK}Learn more{END_LINK} about emailing tasks straight to your Inbox.",
	"INTERFACE_TASKS_INBOX" : "Inbox",
	"INTERFACE_TASKS_SENT" : "Sent",
	"INTERFACE_STATUS_ONE_LIST_DEFAULT" : "You must have only one list selected to set a default list.",
	"INTERFACE_STATUS_MUST_SELECT_DEFAULT" : "You must select a list to set it as your default list.",
	"INTERFACE_STATUS_MUST_SELECT_UNSET_DEFAULT" : "You must select a list to unset your default list.",
	"INTERFACE_STATUS_MUST_SELECT_ONE_OR_MORE_TASKS" : "You have to select one or more tasks to do that...",
	"INTERFACE_STATUS_CANT_MOVE_TO_LIST_ALREADY" : "You can't move tasks to a list they're already in...",
	"INTERFACE_STATUS_NOTHING_TO_UNDO" : "Nothing to undo...",
	"INTERFACE_STATUS_MUST_SELECT_A_CONTACT" : "You have to select a contact to do that...",
	"INTERFACE_STATUS_CANT_CALL_LIST" : "You can't call a list \"{LIST_NAME}\". Sorry.",
	"INTERFACE_STATUS_MUST_SELECT_TO_COMPLETE" : "You have to select something to complete...",
	"INTERFACE_STATUS_MUST_SELECT_TO_UNCOMPLETE" : "You have to select something to uncomplete...",
	"INTERFACE_STATUS_MUST_SELECT_TO_POSTPONE" : "You have to select something to postpone...",
	"INTERFACE_STATUS_MUST_SELECT_TO_DELETE" : "You have to select something to delete...",
	"INTERFACE_STATUS_NOTE_DELETED" : "Note deleted.",
	"INTERFACE_STATUS_NOTE_X_DELETED" : "The note \"{NOTE_TITLE}\" has been deleted.",
	"INTERFACE_STATUS_LIST_RENAMED" : "List renamed to \"{LIST_NAME}\".",
	"INTERFACE_STATUS_REMINDER_SETTINGS_SAVED" : "Reminder settings saved.",
	"INTERFACE_STATUS_PROBLEM_SAVING_CHANGES" : "There was a problem saving the changes. Please try again in a few minutes.",
	"INTERFACE_STATUS_SORRY_EMAIL_IN_USE" : "Sorry, that email address is already in use.",
	"INTERFACE_STATUS_X_SET_AS_DEFAULT_LIST" : "\"{LIST_NAME}\" set as default list.",
	"INTERFACE_STATUS_X_IS_NO_LONGER_DEFAULT" : "\"{LIST_NAME}\" is no longer the default list.",
	"INTERFACE_STATUS_MAKE_X_PUBLIC" : "Making \"{LIST_NAME}\" public...",
	"INTERFACE_STATUS_MAKE_X_PRIVATE" : "Making \"{LIST_NAME}\" private...",
	"INTERFACE_STATUS_CREATING_SMART_LIST" : "Creating Smart List \"{LIST_NAME}\" for current search...",
	"INTERFACE_STATUS_X_IS_NOW_PUBLIC" : "\"{LIST_NAME}\" is now publically viewable.",
	"INTERFACE_STATUS_X_IS_NOW_PRIVATE" : "\"{LIST_NAME}\" is now private.",
	"INTERFACE_STATUS_X_ACCEPTED_FROM_Y" : "List \"{LIST_NAME}\" accepted from \"{CONTACT_NAME}\".",
	"INTERFACE_STATUS_X_HAS_BEEN_INVITED" : "{FIRST_NAME} ({EMAIL}) has been invited to join {RTM}!",
	"INTERFACE_STATUS_X_IS_ALREADY_A_MEMBER" : "{FIRST_NAME} ({EMAIL}) is already a {RTM} member.",
	"INTERFACE_STATUS_MULTI_EDIT_OFF" : "Multi-edit mode off.",
	"INTERFACE_STATUS_MULTI_EDIT_ON" : "Multi-edit mode on.",
	"INTERFACE_STATUS_SMART_LIST_X_CREATED" : "Smart List \"{LIST_NAME}\" created.",
	"INTERFACE_STATUS_SERVICE_DEAUTH" : "The service \"{SERVICE_NAME}\" is no longer authorized to access your account.",
	"INTERFACE_STATUS_BUSY" : "{RTM} is currently really busy, so some things might take a little while to happen. If it's too frustrating, try again in a couple of minutes. (It's okay, we'll still remind you when a task is due.)",
	"INTERFACE_STATUS_NEED_PROVIDE_FIRST_NAME" : "You need to provide a first name...",
	"INTERFACE_STATUS_NEED_PROVIDE_EMAIL" : "You need to provide an email address...",
	"INTERFACE_STATUS_LOADING" : "Loading...",
	"INTERFACE_STATUS_FAILED_AGAIN" : "There was a problem reaching the server. Are you connected to the Internet? ({REQUEST_NAME} failed.) {START_LINK}Try again?{END_LINK}",
	"INTERFACE_STATUS_HAVE_TO_SELECT" : "You have to select something...",
	"INTERFACE_STATUS_CANT_DO_TO_COMPLETED" : "You can't do that to a completed task...",
	"INTERFACE_STATUS_UNDO" : "{START_LINK}Undo?{END_LINK}",
	"INTERFACE_STATUS_UNDOING" : "Undoing...",
	"INTERFACE_STATUS_UNDO_OK" : "Undo OK.",
	"INTERFACE_STATUS_UNDO_FAILED" : "Undo failed.",
	"INTERFACE_STATUS_UNDO_FAILED_TRY_AGAIN" : "Undo failed. {START_LINK}Try again?{END_LINK}",
	"INTERFACE_WELCOME" : "Welcome",
	"INTERFACE_INITIALIZING" : "Initializing...",
	"INTERFACE_TASKS_TASK_DETAILS_TOOLTIP_DUE_DATE" : "Set Due Date {KEY}",
	"INTERFACE_TASKS_TASK_DETAILS_TOOLTIP_REPEAT" : "Set Repeats {KEY}",
	"INTERFACE_TASKS_TASK_DETAILS_TOOLTIP_TIME_ESTIMATE" : "Set Time Estimate {KEY}",
	"INTERFACE_TASKS_TASK_DETAILS_TOOLTIP_TAGS" : "Set Tags {KEY}",
	"INTERFACE_SEARCH_DUE_1_DAY" : "e.g. 1 day",
	"INTERFACE_SEARCH_DUE_TODAY" : "e.g. today, apr 25",
	"INTERFACE_OVERVIEW_NEWS_HEADING" : "{RTM} News",
	"INTERFACE_OVERVIEW_NEWS_POSTED" : "Posted on {DATE}",
	"INTERFACE_STATUS_UNDOING_LAST_ACTION" : "Undoing last action...",
	"INTERFACE_SETTINGS_GENERAL_NOT_SPECIFIED" : "not specified",
	"INTERFACE_SETTINGS_SERVICES_NO_SERVICES" : "You haven't given any third-party services permission to interact with your {RTM} account.",
	"INTERFACE_TASKS_LIST_DETAILS_ICALENDAR_EVENTS_ADD" : "(Events)",
	"INTERFACE_TASKS_TASK_DETAILS_ADD_NOTE" : "Add Note",
	"INTERFACE_TASKS_TASK_DETAILS_ADD_NOTE_KEY" : "Add Note {KEY}",
	"INTERFACE_TASKS_CLOSE_KEY" : "Close Key",
	"INTERFACE_TASKS_KEY" : "Key",
	"INTERFACE_TASKS_KEY_DUE_TODAY" : "Due today:",
	"INTERFACE_TASKS_KEY_OVERDUE" : "Overdue:",
	"INTERFACE_TASKS_KEY_LEARN_KEYBOARD" : "Learn keyboard shortcuts",
	"INTERFACE_TASKS_NO_INCOMPLETE" : "You have no incomplete tasks in this list. Woohoo!",
	"INTERFACE_CONTACTS_GROUPS_NO_GROUPS" : "You have no groups. You should create some!",
	"INTERFACE_CONTACTS_NO_CONTACTS" : "You have no contacts. You should invite some!",
	"INTERFACE_SETTINGS_LISTS_NO_LISTS" : "You have no lists... which is impossible.",
	"INTERFACE_OVERVIEW_NO_TASKS_DUE_TODAY" : "No tasks due today.",
	"INTERFACE_TASKS_NO_COMPLETED" : "You have no completed tasks in this list.",
	"INTERFACE_OVERVIEW_NO_DUE_TOMORROW" : "No tasks due tomorrow.",
	"INTERFACE_OVERVIEW_NO_TASKS_OVERDUE" : "No tasks overdue.",
	"INTERFACE_TASKS_NO_RESULTS" : "No results found.",
	"INTERFACE_TASKS_TIME_ESTIMATE_INVALID" : "I couldn't understand the time estimate entered. Maybe you can try a {START_LINK}time estimate like one of these{END_LINK}.",
	"INTERFACE_TASKS_TASK_DETAILS_NOTES_COUNT_ZERO" : "0 notes",
	"INTERFACE_TASKS_TASK_DETAILS_NOTES_COUNT_ONE" : "1 note",
	"INTERFACE_TASKS_TASK_DETAILS_NOTES_COUNT_NUM" : "{NUM} notes",
	"INTERFACE_TASKS_NOTES_MULTIEDIT" : "(Notes cannot be added or modified while editing multiple tasks.)",
	"INTERFACE_TASKS_NOTES_SAVE_BUTTON" : "Save",
	"INTERFACE_TASKS_NOTES_CANCEL_BUTTON" : "Cancel",
	"INTERFACE_TASKS_NOTES_SAVING_NOTE" : "Saving note...",
	"INTERFACE_TASKS_NOTES_EDIT" : "Edit",
	"INTERFACE_TASKS_NOTES_DELETE" : "Delete Note",
	"INTERFACE_CONTACTS_CONTACT_FORMAT" : "{CONTACT_FIRST_NAME} {CONTACT_LAST_NAME}",
	"INTERFACE_SETTINGS_LISTS_LIST_DEFAULT" : "This is your default list.",
	"INTERFACE_SETTINGS_LIST_PENDING" : "This list is pending acceptance.",
	"INTERFACE_SETTINGS_LIST_SENT_BY_CONTACT" : "It was sent by {CONTACT_FIRST_NAME} {CONTACT_LAST_NAME}, who is one of your contacts.",
	"INTERFACE_SETTINGS_LIST_SENT_BY_NOT_CONTACT" : "It was sent by {CONTACT_FIRST_NAME} {CONTACT_LAST_NAME}, who is not one of your contacts. ({CONTACT_FIRST_NAME} will be added as a contact if you accept the list.)",
	"INTERFACE_SETTINGS_LIST_ACCEPT" : "Accept List",
	"INTERFACE_SETTINGS_LIST_REJECT" : "Reject List",
	"INTERFACE_SETTINGS_REMINDERS_NOTIFY_ON" : "On",
	"INTERFACE_SETTINGS_REMINDERS_NOTIFY_OFF" : "Off",
	"INTERFACE_SETTINGS_REMINDERS_NOTIFY_SAVE" : "Save",
	"INTERFACE_SETTINGS_REMINDERS_NOTIFY_CANCEL" : "Cancel",
	"INTERFACE_SETTINGS_REMINDERS_NOTIFY_SAVING" : "Saving...",
	"INTERFACE_SETTINGS_REMINDERS_NOTIFY_SAVED" : "Saved.",
	"INTERFACE_SETTINGS_INFO_NO_PUBLIC" : "{START_ITALIC}You haven't made any lists public.{END_ITALIC}",
	"INTERFACE_QUICKADD_NEED_TASK_NAME" : "Need a task name",
	"INTERFACE_QUICKADD_UNRECOGNIZED_DATE" : "Unrecognized date",
	"INTERFACE_QUICKADD_MUST_LOGIN" : "You must {START_LINK}login{END_LINK} to add a task.",
	"INTERFACE_QUICKADD_POPUP" : "It looks like you're running a pop-up blocker. Please allow pop-ups from {RTM} before trying to login.",
	"INTERFACE_QUICKADD_TASK_ADDED" : "Task added!",
	"INTERFACE_QUICKADD_ADD_MORE" : "{START_LINK}Add more!{END_LINK} or {START_LINK}close window{END_LINK}.",
	"INTERFACE_QUICKADD_TASK_NAME" : "Task Name",
	"INTERFACE_QUICKADD_DUE_DATE" : "Due Date",
	"INTERFACE_WEEK_SUNDAY" : "Sunday",
	"INTERFACE_WEEK_MONDAY" : "Monday",
	"INTERFACE_WEEK_TUESDAY" : "Tuesday",
	"INTERFACE_WEEK_WEDNESDAY" : "Wednesday",
	"INTERFACE_WEEK_THURSDAY" : "Thursday",
	"INTERFACE_WEEK_FRIDAY" : "Friday",
	"INTERFACE_WEEK_SATURDAY" : "Saturday",
	"INTERFACE_WEEKDAY_SHORT_SUNDAY" : "Sun",
	"INTERFACE_WEEKDAY_SHORT_MONDAY" : "Mon",
	"INTERFACE_WEEKDAY_SHORT_TUESDAY" : "Tue",
	"INTERFACE_WEEKDAY_SHORT_WEDNESDAY" : "Wed",
	"INTERFACE_WEEKDAY_SHORT_THURSDAY" : "Thu",
	"INTERFACE_WEEKDAY_SHORT_FRIDAY" : "Fri",
	"INTERFACE_WEEKDAY_SHORT_SATURDAY" : "Sat",
	"INTERFACE_MONTH_JANUARY" : "January",
	"INTERFACE_MONTH_FEBRUARY" : "February",
	"INTERFACE_MONTH_MARCH" : "March",
	"INTERFACE_MONTH_APRIL" : "April",
	"INTERFACE_MONTH_MAY" : "May",
	"INTERFACE_MONTH_JUNE" : "June",
	"INTERFACE_MONTH_JULY" : "July",
	"INTERFACE_MONTH_AUGUST" : "August",
	"INTERFACE_MONTH_SEPTEMBER" : "September",
	"INTERFACE_MONTH_OCTOBER" : "October",
	"INTERFACE_MONTH_NOVEMBER" : "November",
	"INTERFACE_MONTH_DECEMBER" : "December",
	"INTERFACE_MONTH_SHORT_JAN" : "Jan",
	"INTERFACE_MONTH_SHORT_FEB" : "Feb",
	"INTERFACE_MONTH_SHORT_MAR" : "Mar",
	"INTERFACE_MONTH_SHORT_APR" : "Apr",
	"INTERFACE_MONTH_SHORT_MAY" : "May",
	"INTERFACE_MONTH_SHORT_JUN" : "Jun",
	"INTERFACE_MONTH_SHORT_JUL" : "Jul",
	"INTERFACE_MONTH_SHORT_AUG" : "Aug",
	"INTERFACE_MONTH_SHORT_SEP" : "Sep",
	"INTERFACE_MONTH_SHORT_OCT" : "Oct",
	"INTERFACE_MONTH_SHORT_NOV" : "Nov",
	"INTERFACE_MONTH_SHORT_DEC" : "Dec",
	"INTERFACE_DUE_DATE_EXAMPLE" : "Sat 22 Apr 06",
	"INTERFACE_DUE_DATE_WITH_TIME_EXAMPLE" : "Sat 22 Apr 06 at 1:00PM",
	"INTERFACE_CURRENT_TIME_EXAMPLE" : "Monday, May 22, 2006 | 9:24PM",
	"INTERFACE_TASKS_LIST_DETAILS_SHOW_COMPLETED" : "Show completed tasks",
	"INTERFACE_TASKS_LIST_DETAILS_SHOW_INCOMPLETE" : "Show incomplete tasks",
	"INTERFACE_TASKS_LIST_DETAILS_SEARCHING" : "Searching...",
	"INTERFACE_TASKS_LIST_DETAILS_PUBLISH_DELETED_CONTACTS" : "(Deleted contacts)",
	"INTERFACE_TASKS_TASK_DETAILS_COMPLETED" : "Completed",
	"INTERFACE_TASKS_TASK_DETAILS_URL" : "URL",
	"INTERFACE_TASKS_TASK_DETAILS_SENT_TO" : "Sent to",
	"INTERFACE_TASKS_TASK_DETAILS_SHOW_NOTES" : "Show notes for this task",
	"INTERFACE_TASKS_TASK_DETAILS_SHOW_LIST_FOR_TAG" : "Show list for tag {TAG}",
	"INTERFACE_TASKS_TASK_DETAILS_SHOW_CONTACT" : "Show contact details",
	"INTERFACE_STATUS_CONTACT_DELETED_ONE" : "\"{CONTACT_NAME}\" deleted.",
	"INTERFACE_STATUS_CONTACT_DELETED_NUM" : "{NUM} contacts deleted.",
	"INTERFACE_STATUS_GROUP_DELETED_ONE" : "\"{GROUP_NAME}\" deleted.",
	"INTERFACE_STATUS_GROUP_DELETED_NUM" : "{NUM} groups deleted.",
	"INTERFACE_STATUS_CONTACT_GROUP_ADD_ONE" : "\"{CONTACT_NAME}\" added to \"{GROUP_NAME}\" group.",
	"INTERFACE_STATUS_CONTACT_GROUP_ADD_NUM" : "{NUM} contacts added to \"{GROUP_NAME}\" group.",
	"INTERFACE_STATUS_CONTACT_GROUP_REMOVE_ONE" : "\"{CONTACT_NAME}\" removed from \"{GROUP_NAME}\" group.",
	"INTERFACE_STATUS_CONTACT_GROUP_REMOVE_NUM" : "{NUM} contacts removed from \"{GROUP_NAME}\" group.",
	"INTERFACE_STATUS_LIST_ARCHIVED_ONE" : "\"{LIST_NAME}\" archived.",
	"INTERFACE_STATUS_LIST_UNARCHIVED_ONE" : "\"{LIST_NAME}\" unarchived.",
	"INTERFACE_STATUS_LIST_ARCHIVED_NUM" : "{NUM} lists archived.",
	"INTERFACE_STATUS_LIST_UNARCHIVED_NUM" : "{NUM} lists unarchived.",
	"INTERFACE_STATUS_LIST_ARCHIVE_MUST_SELECT" : "You have to select something to archive...",
	"INTERFACE_STATUS_LIST_UNARCHIVE_MUST_SELECT" : "You have to select something to unarchive...",
	"INTERFACE_STATUS_CANNOT_ARCHIVE_LOCKED_ONE" : "Sorry, you can't archive \"{LIST_NAME}\" because it is locked.",
	"INTERFACE_STATUS_CANNOT_ARCHIVE_LOCKED_NUM" : "Sorry, you can't archive \"{LIST_NAMES}\" because they are locked.",
	"INTERFACE_STATUS_CANNOT_ARCHIVE_PENDING_ONE" : "Sorry, you can't archive \"{LIST_NAME}\" because it is pending acceptance.",
	"INTERFACE_STATUS_CANNOT_ARCHIVE_PENDING_NUM" : "Sorry, you can't archive \"{LIST_NAMES}\" because they are pending acceptance.",
	"INTERFACE_STATUS_TASK_TIME_ESTIMATE_ONE" : "Time estimate for \"{TASK_NAME}\" changed.",
	"INTERFACE_STATUS_TASK_TIME_ESTIMATE_NUM" : "Time estimate for {NUM} tasks changed.",
	"INTERFACE_STATUS_TASK_URL_ONE" : "URL for \"{TASK_NAME}\" changed.",
	"INTERFACE_STATUS_TASK_URL_NUM" : "URL for {NUM} tasks changed.",
	"INTERFACE_TASKS_REPEAT_INVALID" : "I couldn't understand the repeat interval entered. Maybe you could try a {START_LINK}repeat interval like one of these{END_LINK}.",
	"INTERFACE_STATUS_TASK_TAG_REMOVE_ONE_FROM_ONE" : "Removed tag \"{TAG_NAME}\" from \"{TASK_NAME}\".",
	"INTERFACE_STATUS_TASK_TAG_REMOVE_ONE_FROM_NUM" : "Removed tag \"{TAG_NAME}\" from {NUM} tasks.",
	"INTERFACE_STATUS_TASK_TAG_REMOVE_NUM_FROM_ONE" : "Removed {TAG_NUM} tags from \"{TASK_NAME}\".",
	"INTERFACE_STATUS_TASK_TAG_REMOVE_NUM_FROM_NUM" : "Removed {TAG_NUM} tags from {TASK_NUM} tasks.",
	"INTERFACE_STATUS_TASK_TAG_ONE" : "Tagged \"{TASK_NAME}\" with \"{TAGS}\".",
	"INTERFACE_STATUS_TASK_TAG_NUM" : "Tagged {NUM} tasks with \"{TAGS}\".",
	"INTERFACE_STATUS_TASK_DUE_DATE_ONE" : "Due date for \"{TASK_NAME}\" changed.",
	"INTERFACE_STATUS_TASK_DUE_DATE_NUM" : "Due date for {NUM} tasks changed.",
	"INTERFACE_TASKS_DUE_DATE_INVALID" : "I couldn't understand the date entered. Maybe you can try a {START_LINK}date format like one of these{END_LINK}.",
	"INTERFACE_STATUS_TASK_REPEAT_ONE" : "\"{TASK_NAME}\" will repeat {REPEAT_FORMAT}.",
	"INTERFACE_STATUS_TASK_REPEAT_NUM" : "{NUM} tasks will repeat {REPEAT_FORMAT}.",
	"INTERFACE_STATUS_TASK_NO_REPEAT_ONE" : "\"{TASK_NAME}\" will not repeat.",
	"INTERFACE_STATUS_TASK_NO_REPEAT_NUM" : "{NUM} tasks will not repeat.",
	"INTERFACE_STATUS_TASK_COMPLETED_ONE" : "\"{TASK_NAME}\" completed.",
	"INTERFACE_STATUS_TASK_COMPLETED_ONE_GENERATED_NUM" : "\"{TASK_NAME}\" completed. {GENERATED_NUM} tasks generated.",
	"INTERFACE_STATUS_TASK_COMPLETED_NUM" : "{NUM} tasks completed.",
	"INTERFACE_STATUS_TASK_COMPLETED_NUM_GENERATED_NUM" : "{NUM} tasks completed. {GENERATED_NUM} tasks generated.",
	"INTERFACE_STATUS_TASK_UNCOMPLETED_ONE" : "\"{TASK_NAME}\" uncompleted.",
	"INTERFACE_STATUS_TASK_UNCOMPLETED_NUM" : "{NUM} tasks uncompleted.",
	"INTERFACE_STATUS_TASK_DELETED_ONE" : "\"{TASK_NAME}\" deleted.",
	"INTERFACE_STATUS_TASK_DELETED_NUM" : "{NUM} tasks deleted.",
	"INTERFACE_STATUS_TASK_POSTPONED_ONE" : "\"{TASK_NAME}\" postponed.",
	"INTERFACE_STATUS_TASK_POSTPONED_NUM" : "{NUM} tasks postponed.",
	"INTERFACE_STATUS_TASK_PRIORITY_ONE" : "Changed priority of \"{TASK_NAME}\".",
	"INTERFACE_STATUS_TASK_PRIORITY_NUM" : "Changed priority of {NUM} tasks.",
	"INTERFACE_STATUS_TASK_RENAME_ONE" : "Task renamed to \"{TASK_NAME}\".",
	"INTERFACE_STATUS_TASK_RENAME_NUM" : "{NUM} tasks renamed to \"{TASK_NAME}\".",
	"INTERFACE_STATUS_CANNOT_DELETE_LOCKED_ONE" : "Sorry, you can't delete \"{LIST_NAME}\" because it is locked.",
	"INTERFACE_STATUS_CANNOT_DELETE_LOCKED_NUM" : "Sorry, you can't delete \"{LIST_NAMES}\" because they are locked.",
	"INTERFACE_STATUS_CANNOT_DELETE_PENDING_ONE" : "Sorry, you can't delete \"{LIST_NAME}\" because it is pending acceptance.",
	"INTERFACE_STATUS_CANNOT_DELETE_PENDING_NUM" : "Sorry, you can't delete \"{LIST_NAMES}\" because they are pending acceptance.",
	"INTERFACE_STATUS_LIST_SMART_DELETED" : "Smart List \"{LIST_NAME}\" deleted.",
	"INTERFACE_STATUS_LIST_DELETED_ONE" : "List \"{LIST_NAME}\" deleted.",
	"INTERFACE_STATUS_LIST_DELETED_ONE_TASK_ONE" : "List \"{LIST_NAME}\" deleted. \"{TASK_NAME}\" moved to Inbox.",
	"INTERFACE_STATUS_LIST_DELETED_ONE_TASK_NUM" : "List \"{LIST_NAME}\" deleted. {TASK_NUM} tasks moved to Inbox.",
	"INTERFACE_STATUS_LIST_DELETED_NUM" : "{NUM} lists deleted.",
	"INTERFACE_STATUS_LIST_DELETED_NUM_TASK_ONE" : "{NUM} lists deleted. \"{TASK_NAME}\" moved to Inbox.",
	"INTERFACE_STATUS_LIST_DELETED_NUM_TASK_NUM" : "{NUM} lists deleted. {TASK_NUM} tasks moved to Inbox.",
	"INTERFACE_STATUS_TASK_MOVED_ONE" : "\"{TASK_NAME}\" moved from \"{ORIGIN_LIST_NAME}\" to \"{TARGET_LIST_NAME}\".",
	"INTERFACE_STATUS_TASK_MOVED_NUM" : "{TASK_NUM} tasks moved from \"{ORIGIN_LIST_NAME}\" to \"{TARGET_LIST_NAME}\".",
	"INTERFACE_STATUS_TASK_MOVED_NUM_LIST_NUM" : "{TASK_NUM} tasks moved from {LIST_NUM} lists to \"{TARGET_LIST_NAME}\".",
	"INTERFACE_STATUS_REMINDER_ON" : "Reminders for \"{NOTIFICATION_MECH}\" turned on.",
	"INTERFACE_STATUS_REMINDER_OFF" : "Reminders for \"{NOTIFICATION_MECH}\" turned off.",
	"INTERFACE_STATUS_SETTINGS_SAVED_EXCEPT_EMAIL" : "Settings saved. (Except for the email address, which is already in use.)",
	"INTERFACE_STATUS_SETTINGS_SAVED" : "Settings saved.",
	"INTERFACE_TASKS_REMINDERS_IM_ADD" : "(You may need to add \"{IM_ADDRESS}\" to your buddy list.)",
	"INTERFACE_TASKS_REMINDERS_EMAIL_PENDING" : "(Pending email verification.)",
	"INTERFACE_TASKS_REMINDERS_MOBILE_PENDING" : "(Pending mobile verification.)",
	"INTERFACE_TASKS_REMINDERS_NO_LIMIT" : "(No limit per day.)",
	"INTERFACE_TASKS_REMINDERS_NUM_LIMIT" : "(Limited to {NUM} per day.)",
	"INTERFACE_STATUS_REMINDERS_NOTIFY_DETAILS" : "Reminders will be sent to \"{NOTIFICATION_MECH}\".",
	"INTERFACE_STATUS_REMINDERS_NOTIFY_NO_MORE" : "Reminders will not be sent to \"{NOTIFICATION_MECH}\" anymore.",
	"INTERFACE_STATUS_REMINDERS_NOTIFY_DETAILS_ADDITIONAL" : "Reminders will be sent to \"{NOTIFICATION_MECH}\". {ADDITIONAL_INFORMATION}",
	"INTERFACE_STATUS_X_REJECTED_FROM_Y" : "List \"{LIST_NAME}\" rejected (from \"{CONTACT_NAME}\").",
	"INTERFACE_STATUS_LIST_REJECTED" : "List \"{LIST_NAME}\" rejected.",
	"INTERFACE_CONTACTS_SELECT_SOME_CONTACTS_OR_GROUPS" : "Select some contacts and\/or groups.",
	"INTERFACE_CONTACTS_SEL_ONE_ONE" : "1 contact and 1 group selected.",
	"INTERFACE_CONTACTS_SEL_ONE_NUM" : "1 contact and {GROUP_NUM} groups selected.",
	"INTERFACE_CONTACTS_SEL_NUM_ONE" : "{CONTACT_NUM} contacts and 1 group selected.",
	"INTERFACE_CONTACTS_SEL_NUM_NUM" : "{CONTACT_NUM} contacts and {GROUP_NUM} groups selected.",
	"INTERFACE_CONTACTS_INVITES_SENDING" : "Sending...",
	"INTERFACE_PLEASE_WAIT" : "Please wait.",
	"INTERFACE_TRYING" : "Trying...",
	"INTERFACE_TOOLTIP_RENAME" : "Rename {KEY}",
	"INTERFACE_TASKS_TASK_DETAILS_TOOLTIP_URL" : "Set URL {KEY}",
	"INTERFACE_SECURING_COMMUNICATIONS" : "Securing communications...",
	"INTERFACE_WELCOME_SALUTATION" : "{FIRST_NAME} {LAST_NAME}",
	"INTERFACE_TRY_OUT_RTM" : "Try out {RTM}",
	"INTERFACE_PERSONAL_LIST" : "Personal",
	"INTERFACE_WORK_LIST" : "Work",
	"INTERFACE_STUDY_LIST" : "Study",
	"INTERFACE_PUBLISHING_X_TO" : "Publishing \"{LIST_NAME}\" to...",
	"INTERFACE_SHARING_X_WITH" : "Sharing \"{LIST_NAME}\" with...",
	"INTERFACE_SENDING_TASK_TO" : "Sending \"{TASK_NAME}\" to...",
	"INTERFACE_SENDING_NUM_TASK_TO" : "Sending {TASK_NUM} tasks to...",
	"INTERFACE_SHARING_TASK_WITH" : "Sharing \"{TASK_NAME}\" with...",
	"INTERFACE_SHARING_NUM_TASKS_WITH" : "Sharing {TASK_NUM} tasks with...",
	"INTERFACE_SENDING_TASK_TO_DONE" : "Sending \"{TASK_NAME}\". Done. Moved to Sent.",
	"INTERFACE_SENDING_NUM_TASK_TO_DONE" : "Sending {TASK_NUM} tasks. Done. Moved to Sent.",
	"INTERFACE_SHARING_TASK_WITH_DONE" : "Sharing \"{TASK_NAME}\". Done.",
	"INTERFACE_SHARING_NUM_TASKS_WITH_DONE" : "Sharing {TASK_NUM} tasks. Done.",
	"INTERFACE_SENDING_TASK_TO_DONE_WITH_FAILED" : "Sending \"{TASK_NAME}\". Couldn't send task to \"{FAILED_CONTACTS}\" because they don't have you in their contacts list.",
	"INTERFACE_SENDING_TASK_TO_DONE_WITH_SUCCESS" : "Sending \"{TASK_NAME}\". Sent to \"{SUCCESS_CONTACTS}\". Moved to Sent. Couldn't send task to \"{FAILED_CONTACTS}\" because they don't have you in their contacts list.",
	"INTERFACE_SENDING_NUM_TASK_TO_DONE_FAILED" : "Sending {TASK_NUM} tasks. Couldn't send tasks to \"{FAILED_CONTACTS}\" because they don't have you in their contacts list.",
	"INTERFACE_SENDING_NUM_TASK_TO_DONE_SUCCESS" : "Sending {TASK_NUM} tasks. Sent to \"{SUCCESS_CONTACTS}\". Moved to Sent. Couldn't send tasks to \"{FAILED_CONTACTS}\" because they don't have you in their contacts list.",
	"INTERFACE_SHARING_TASK_WITH_SUCCESS" : "Sharing \"{TASK_NAME}\". Shared with \"{SUCCESS_CONTACTS}\". Couldn't share task with \"{FAILED_CONTACTS}\" because they don't have you in their contacts list.",
	"INTERFACE_SHARING_TASK_WITH_FAILED" : "Sharing \"{TASK_NAME}\". Couldn't share task with \"{FAILED_CONTACTS}\" because they don't have you in their contacts list.",
	"INTERFACE_SHARING_NUM_TASKS_WITH_SUCCESS" : "Sharing {TASK_NUM} tasks. Shared with \"{SUCCESS_CONTACTS}\". Couldn't share tasks with \"{FAILED_CONTACTS}\" because they don't have you in their contacts list.",
	"INTERFACE_SHARING_NUM_TASKS_WITH_FAILED" : "Sharing {TASK_NUM} tasks. Couldn't share tasks with \"{FAILED_CONTACTS}\" because they don't have you in their contacts list.",
	"INTERFACE_KEY_BOLD" : "bold",
	"INTERFACE_KEY_UNDERLINE" : "underline",
	"INTERFACE_KEY_NO" : "No",
	"INTERFACE_KEY_PRIORITIES" : "Priorities:",
	"INTERFACE_HEADING_TASKS_PUBLIC" : "{FIRST_NAME} Public Tasks",
	"INTERFACE_WEEKLY_PLANNER_WEEK_BEGINNING" : "Week beginning {START_BOLD}{DATE}{END_BOLD}",
	"INTERFACE_LANGUAGE" : "Language",
	"INTERFACE_MULTIPLE" : "Multiple",
	"INTERFACE_TYPE_WEEK" : "week",
	"INTERFACE_TYPE_DAY" : "day",
	"INTERFACE_TYPE_MONTH" : "month",
	"INTERFACE_TYPE_YEAR" : "year",
	"INTERFACE_BUTTON_SEND" : "Send",
	"INTERFACE_DF_IN_A_MONTH" : "in a month",
	"INTERFACE_DF_NEXT_DAY_NAME" : "next {DAY_NAME}",
	"INTERFACE_DF_1_YEAR" : "1 year",
	"INTERFACE_DF_IN_A_MINUTE" : "in a minute",
	"INTERFACE_DF_NUM_MONTHS" : "{NUM} months",
	"INTERFACE_DF_END_OF_MONTH_NAME" : "end of {MONTH_NAME}",
	"INTERFACE_DF_END_OF_MONTH" : "end of the month",
	"INTERFACE_DF_YEARLY" : "yearly",
	"INTERFACE_DF_IN_NUM_DAYS" : "in {NUM} days",
	"INTERFACE_DF_DAY_NAME_AND_DAY_NAME" : "{DAY_NAME} and {DAY_NAME}",
	"INTERFACE_DF_1_MONTH" : "1 month",
	"INTERFACE_DF_AFTER_INTERVAL" : "after {INTERVAL}",
	"INTERFACE_DF_IN_NUM_YEARS" : "in {NUM} years",
	"INTERFACE_DF_IN_1_MONTH" : "in 1 month",
	"INTERFACE_DF_IN_1_HOUR" : "in 1 hour",
	"INTERFACE_DF_IN_1_DAY" : "in 1 day",
	"INTERFACE_DF_IN_1_MINUTE" : "in 1 minute",
	"INTERFACE_DF_MONTHLY" : "monthly",
	"INTERFACE_DF_IN_1_YEAR" : "in 1 year",
	"INTERFACE_DF_WEEKLY" : "weekly",
	"INTERFACE_DF_MIDDAY" : "midday",
	"INTERFACE_DF_IN_A_WEEK" : "in a week",
	"INTERFACE_DF_IN_A_DAY" : "in a day",
	"INTERFACE_DF_MIDNIGHT" : "midnight",
	"INTERFACE_DF_IN_NUM_MONTHS" : "in {NUM} months",
	"INTERFACE_DF_IN_A_YEAR" : "in a year",
	"INTERFACE_DF_IN_NUM_HOURS" : "in {NUM} hours",
	"INTERFACE_DF_IN_1_WEEK" : "in 1 week",
	"INTERFACE_DF_IN_NUM_WEEKS" : "in {NUM} weeks",
	"INTERFACE_DF_WEEKEND" : "weekend",
	"INTERFACE_DF_NUM_YEARS" : "{NUM} years",
	"INTERFACE_DF_1_WEEK" : "1 week",
	"INTERFACE_DF_NUM_WEEKS" : "{NUM} weeks",
	"INTERFACE_DF_WEEKDAY" : "weekday",
	"INTERFACE_DF_EVERY_INTERVAL" : "every {INTERVAL}",
	"INTERFACE_DF_DAILY" : "daily",
	"INTERFACE_DF_IN_NUM_MINUTES" : "in {NUM} minutes",
	"INTERFACE_DF_IN_AN_HOUR" : "in an hour",
	"INTERFACE_DF_EVERY_DAY_NAME_UNTIL_DATE" : "every {DAY_NAME} until {DATE}",
	"INTERFACE_DF_EVERY_DAY_NAME_FOR_NUM_TIMES" : "every {DAY_NAME} for {NUM} times",
	"INTERFACE_TASKS_TASK_DETAILS_URL_NONE" : "none",
	"INTERFACE_SETTINGS_TASK_CLOUD_LABEL" : "Task Cloud",
	"INTERFACE_SETTINGS_TASK_CLOUD_SHOW" : "Show Task Cloud on the Tasks screen",
	"INTERFACE_SETTINGS_CLOSE_ACCOUNT_LABEL" : "Close Account",
	"INTERFACE_SETTINGS_CLOSE_ACCOUNT_TEXT" : "Close your account",
	"INTERFACE_LOCATIONS_ADD_LOCATION" : "Add Location",
	"INTERFACE_LOCATIONS_MANAGE_LOCATIONS" : "Manage Locations",
	"INTERFACE_LOCATIONS_TOOLTIP_ADD" : "Add {KEY}",
	"INTERFACE_TASKS_TASK_DETAILS_LOCATION" : "Location",
	"INTERFACE_LOCATIONS_CLICK_DESIRED" : "Click on the map to create a new location. {START_LINK}Cancel?{END_LINK}",
	"INTERFACE_LOCATIONS_IW_SAVE_LOCATION" : "Save Location",
	"INTERFACE_LOCATIONS_IW_SAVE_BUTTON" : "Save",
	"INTERFACE_LOCATIONS_STATUS_TASK_NAME_CHANGED" : "Location for \"{TASK_NAME}\" changed.",
	"INTERFACE_LOCATIONS_STATUS_NUM_TASKS_CHANGED" : "Location for {NUM} tasks changed.",
	"INTERFACE_STATUS_ONE_LOCATION_DEFAULT" : "You must have only one location selected to set a default location.",
	"INTERFACE_STATUS_LOCATION_MUST_SELECT_UNSET_DEFAULT" : "You must select a location to unset your default location.",
	"INTERFACE_STATUS_LOCATION_MUST_SELECT_DEFAULT" : "You must select a location to set it as your default location.",
	"INTERFACE_SETTINGS_LOCATIONS_TOOLBOX_DELETE_LOCATION" : "Delete Location",
	"INTERFACE_SETTINGS_LOCATIONS_STATUS_LOCATION_DELETED" : "Location \"{LOCATION_NAME}\" deleted.",
	"INTERFACE_SETTINGS_LOCATIONS_STATUS_LOCATION_NUM_DELETED" : "{NUM} locations deleted.",
	"INTERFACE_SETTINGS_LOCATIONS_ZERO_LOCATIONS" : "0 locations",
	"INTERFACE_SETTINGS_LOCATIONS_ONE_LOCATION" : "1 location",
	"INTERFACE_SETTINGS_LOCATIONS_NUM_LOCATIONS" : "{NUM} locations",
	"INTERFACE_SETTINGS_LOCATIONS_TAB" : "Locations",
	"INTERFACE_SETTINGS_LOCATIONS_SELECTED_ONE" : "1 location selected.",
	"INTERFACE_SETTINGS_LOCATIONS_SELECTED_NUM" : "{NUM} locations selected.",
	"INTERFACE_TASKS_TASK_DETAILS_TOOLTIP_LOCATION" : "Set Location {KEY}",
	"INTERFACE_TASKS_TASK_DETAILS_LOCATION_NONE" : "none",
	"INTERFACE_LOCATIONS_UNABLE_TO_FIND" : "Unable to find location.",
	"INTERFACE_LOCATIONS_LOCATION_SAVED" : "Location \"{LOCATION_NAME}\" saved.",
	"INTERFACE_LOCATIONS_LOCATION_SAVED_AT_ADDRESS" : "Location \"{LOCATION_NAME}\" saved at \"{LOCATION_ADDRESS}\".",
	"INTERFACE_LOCATIONS_MAP_TYPE_MAP" : "Map",
	"INTERFACE_LOCATIONS_MAP_TYPE_HYBRID" : "Hybrid",
	"INTERFACE_LOCATIONS_MAP_TYPE_SATELLITE" : "Satellite",
	"INTERFACE_LOCATIONS_TIME_FILTER_FOREVER" : "Forever",
	"INTERFACE_LOCATIONS_GO_BUTTON" : "Go",
	"INTERFACE_LOCATIONS_SHOW_TASKS_WITH_NO_DUE_DATE" : "Show tasks with no due date",
	"INTERFACE_SETTINGS_LOCATIONS_NO_LOCATIONS" : "You have no locations. You should create some!",
	"INTERFACE_HELP_REMINDERS_USERNAME" : "Enter the username for your mobile service.",
	"INTERFACE_HELP_LOCATIONS" : "Manage your locations.",
	"INTERFACE_LOCATIONS_IW_PREV" : "prev",
	"INTERFACE_LOCATIONS_IW_NEXT" : "next",
	"INTERFACE_LOCATIONS_ALREADY_HAVE" : "You already have a location named \"{LOCATION_NAME}\". Please choose another name.",
	"INTERFACE_SETTINGS_LOCATIONS_LOCATION_DEFAULT" : "This is your default location.",
	"INTERFACE_SETTINGS_LOCATIONS_ADDRESS" : "Address: {LOCATION_ADDRESS}",
	"INTERFACE_LOCATIONS_SHOW_TASKS_FOR_THIS_LOCATION" : "Show tasks for this location.",
	"INTERFACE_LOCATIONS_FOUND_ONE" : "Found \"{LOCATION_NAME}\" at \"{LOCATION_ADDRESS}\".",
	"INTERFACE_LOCATIONS_FOUND_MORE" : "Found {NUM} locations for \"{LOCATION_NAME}\".",
	"INTERFACE_TASKS_TASK_DETAILS_LOCATION_TOOLTIP" : "Show location on map",
	"INTERFACE_LOCATIONS_LOCATION_RENAMED" : "Location renamed to \"{LOCATION_NAME}\".",
	"INTERFACE_TASKS_LOCATION_INVALID" : "Location \"{LOCATION_NAME}\" was not found. Please try {START_LINK}adding a location{END_LINK}.",
	"INTERFACE_LOCATIONS_NO_GOOGLE_MAPS" : "There was a problem loading Google Maps. The Locations feature has been disabled.",
	"INTERFACE_TASKS_TASK_DETAILS_ADDED" : "Added",
	"INTERFACE_STATUS_MAX_DUPLICATE" : "You can only duplicate {NUM} tasks at a time.",
	"INTERFACE_TASKS_TOOLBOX_DUPLICATE_TASK" : "Duplicate Task",
	"INTERFACE_STATUS_SMART_LIST_UPDATED" : "Smart List criteria for \"{LIST_NAME}\" updated.",
	"INTERFACE_STATUS_TASK_DUPLICATED_ONE" : "\"{TASK_NAME}\" duplicated.",
	"INTERFACE_STATUS_TASK_DUPLICATED_NUM" : "{NUM} tasks duplicated.",
	"INTERFACE_DIALOG_LOCATIONS_DISABLED_TITLE" : "The Locations feature is disabled.",
	"INTERFACE_DIALOG_LOCATIONS_DISABLED_TEXT" : "The Locations feature is unavailable while in {START_BOLD}offline{END_BOLD} mode.",
	"INTERFACE_OFFLINE_ICON_ONLINE" : "Currently online: click to go offline",
	"INTERFACE_OFFLINE_ICON_OFFLINE" : "Currently offline: click to go online",
	"INTERFACE_OFFLINE_ICON_SYNC" : "Synchronizing...",
	"INTERFACE_OFFLINE" : "Offline",
	"INTERFACE_DIALOG_DISABLED_ACTION_TITLE" : "{RTM} is currently in offline mode.",
	"INTERFACE_DIALOG_DISABLED_ACTION_TEXT" : "The action you attempted can't be performed while {START_BOLD}offline{END_BOLD}. If your computer is connected to the Internet, you can switch back to {START_BOLD}online{END_BOLD} mode then perform this action.",
	"INTERFACE_DIALOG_DISABLED_ACTION_BUTTON_OK" : "Go online",
	"INTERFACE_DIALOG_DISABLED_ACTION_BUTTON_CANCEL" : "Stay in offline mode",
	"INTERFACE_DIALOG_CONNECTION_LOST_TITLE" : "{RTM} has switched to offline mode.",
	"INTERFACE_DIALOG_CONNECTION_LOST_TEXT" : "{RTM} could not access the Internet, and has switched to {START_BOLD}offline{END_BOLD} mode. Some operations may not be available until {START_BOLD}online{END_BOLD} mode is restored.",
	"INTERFACE_DIALOG_CONNECTION_LOST_BUTTON_OK" : "OK",
	"INTERFACE_DIALOG_DELETE_TASK_TITLE_ONE" : "Delete task?",
	"INTERFACE_DIALOG_DELETE_TASK_TITLE_NUM" : "Delete tasks?",
	"INTERFACE_DIALOG_DELETE_TASK_TEXT_ONE" : "Are you sure you want to delete \"{TASK_NAME}\"? There is no {START_BOLD}undo{END_BOLD} in {START_BOLD}offline{END_BOLD} mode.",
	"INTERFACE_DIALOG_DELETE_TASK_TEXT_NUM" : "Are you sure you want to delete the {NUM} selected tasks? There is no {START_BOLD}undo{END_BOLD} in {START_BOLD}offline{END_BOLD} mode.",
	"INTERFACE_DIALOG_LOGGED_OUT_TITLE" : "Please Login",
	"INTERFACE_DIALOG_LOGGED_OUT_TEXT" : "It looks like you're not {START_BOLD}logged in{END_BOLD} to {RTM}. To continue, please {START_BOLD}login{END_BOLD} then {START_BOLD}try again{END_BOLD}.",
	"INTERFACE_DIALOG_LOGGED_OUT_BUTTON_OK" : "Try Again",
	"INTERFACE_DIALOG_GEARS_TITLE" : "Set up {RTM} for offline use.",
	"INTERFACE_DIALOG_GEARS_TEXT_1" : "This feature enables you to manage your tasks even when your computer is not connected to the Internet.",
	"INTERFACE_DIALOG_GEARS_TEXT_2" : "To use the offline features of {RTM}, you will first need to install the Google Gears plug-in for your browser.",
	"INTERFACE_DIALOG_GEARS_TEXT_3" : "Please note:",
	"INTERFACE_DIALOG_GEARS_TEXT_4" : "Installing Google Gears requires that you restart your browser, so we recommend you close all other browser windows before you begin.",
	"INTERFACE_DIALOG_GEARS_BUTTON_OK" : "Install Google Gears",
	"INTERFACE_GOOGLE_GEARS_MESSAGE" : "You can enable offline mode for {RTM} by installing Google Gears.",
	"INTERFACE_OFFLINE_STATUS_SHOW_ONLINE" : "To use {RTM} in {START_BOLD}offline mode{END_BOLD}, click the icon above.",
	"INTERFACE_OFFLINE_STATUS_DISMISS" : "Dismiss this message",
	"INTERFACE_OFFLINE_STATUS_OFFLINE" : "You are in {START_BOLD}offline{END_BOLD} mode.",
	"INTERFACE_OFFLINE_STATUS_GO_ONLINE" : "Go online",
	"INTERFACE_OFFLINE_STATUS_START" : "Status: {STATUS_MESSAGE}",
	"INTERFACE_OFFLINE_STATUS_UPDATING" : "Updating for offline use",
	"INTERFACE_OFFLINE_STATUS_SYNC" : "Synchronizing",
	"INTERFACE_OFFLINE_STATUS_PLEASE_WAIT" : "Please wait...",
	"INTERFACE_OFFLINE_STATUS_SHOW_READY" : "Ready for offline use! You can go offline at any time (or, click the icon above to manually switch to {START_BOLD}offline mode{END_BOLD}).",
	"INTERFACE_OFFLINE_ICON_UPDATING" : "Updating for offline use...",
	"INTERFACE_SORT_BY_BUTTON" : "Sort by...",
	"INTERFACE_PRO_STATUS_PRO_FIRST" : "You have a {RTM} {START_LINK}Pro account{END_LINK}. It expires on {START_BOLD}{EXPIRE_DATE}{END_BOLD}.",
	"INTERFACE_PRO_STATUS_PRO_SECOND" : "{START_LINK}Extend your Pro account{END_LINK}, {START_LINK}view your order history{END_LINK}, or {START_LINK}view the gifts you've purchased{END_LINK}.",
	"INTERFACE_PRO_STATUS_FREE_FIRST" : "You have a free {RTM} account, which you can {START_LINK}upgrade{END_LINK} to a Pro account.",
	"INTERFACE_PRO_STATUS_FREE_SECOND" : "You can also {START_LINK}view your order history{END_LINK} or {START_LINK}view the gifts you've purchased{END_LINK}.",
	"INTERFACE_SYNC_TITLE" : "Sync",
	"INTERFACE_SYNC_MENU" : "Menu",
	"INTERFACE_SYNC_ACCOUNT" : "Account",
	"INTERFACE_SYNC_SETTINGS" : "Sync Settings",
	"INTERFACE_SYNC_TOOLS" : "Tools",
	"INTERFACE_SYNC_RESTORE" : "Restore",
	"INTERFACE_SYNC_LOGGING" : "Logging",
	"INTERFACE_SYNC_EXIT" : "Exit",
	"INTERFACE_SYNC_STOP" : "Stop",
	"INTERFACE_SYNC_CLOSE" : "Close",
	"INTERFACE_SYNC_VIEW" : "View",
	"INTERFACE_SYNC_MILKSYNC_ALERT" : "{MILKSYNC} alert",
	"INTERFACE_SYNC_ERROR_NO_MEM" : "Out of memory.",
	"INTERFACE_SYNC_ERROR_LOW_MEM" : "Low storage memory. Synchronization stopped.",
	"INTERFACE_SYNC_ERROR_SERVER_FAIL" : "Server failure. Synchronization not completed.",
	"INTERFACE_SYNC_MSG_FULL_SYNC" : "The server has requested a full sync. This may take a few minutes depending on the amount of data and network speed. Continue?\r\n",
	"INTERFACE_SYNC_MSG_RESTORE" : "Replacing your device's tasks with a fresh copy from the server. Continue?\r\n",
	"INTERFACE_SYNC_MSG_SEND_RECV" : "Send\/Receive in progress...",
	"INTERFACE_SYNC_ERROR_PROGRAM" : "\"{PROGRAM}\" was not found. Please reinstall the application.",
	"INTERFACE_SYNC_TITLE_LOG" : "Log Level:",
	"INTERFACE_SYNC_LOG_ERROR" : "Error",
	"INTERFACE_SYNC_ERROR_INFO" : "Info",
	"INTERFACE_SYNC_LOG_DEBUG" : "Debug",
	"INTERFACE_SYNC_MSG_LOG" : "To see the latest log, select \u201cView\u201d.",
	"INTERFACE_SYNC_TITLE_ACCOUNT" : "Account Details",
	"INTERFACE_SYNC_MSG_ACCOUNT" : "Please enter your {RTM_SHORT} account details.",
	"INTERFACE_SYNC_TITLE_DEVICE" : "Device Info",
	"INTERFACE_SYNC_DEVICE_ID" : "Device ID:",
	"INTERFACE_SYNC_DEVICE_IP" : "Current IP:",
	"INTERFACE_SYNC_STATUS_READY" : "Ready to sync",
	"INTERFACE_SYNC_STATUS_NOT" : "Not synchronized",
	"INTERFACE_SYNC_STATUS_LAST" : "Last sync:",
	"INTERFACE_SYNC_STATUS_LAST_FAILED" : "Last sync failed",
	"INTERFACE_SYNC_STATUS_LAST_CANCELLED" : "Last sync cancelled",
	"INTERFACE_SYNC_STATUS_CHECKING" : "Checking network...",
	"INTERFACE_SYNC_STATUS_CONNECTING" : "Connecting...",
	"INTERFACE_SYNC_STATUS_START" : "Starting sync...",
	"INTERFACE_SYNC_STATUS_WAITING" : "Waiting for server data...",
	"INTERFACE_SYNC_STATUS_FINISHED_RECV" : "Finished receiving",
	"INTERFACE_SYNC_STATUS_CHECK" : "Checking",
	"INTERFACE_SYNC_STATUS_SENDING" : "Sending",
	"INTERFACE_SYNC_STATUS_RECV" : "Receiving",
	"INTERFACE_SYNC_STATUS_ENDING" : "Ending...",
	"INTERFACE_SYNC_STATUS_SUCCESS" : "Synchronization successful.",
	"INTERFACE_SYNC_ERROR_PROBLEM" : "There was a problem contacting {RTM}. Please try again in a few minutes.",
	"INTERFACE_SYNC_ERROR_FAILED" : "Failed",
	"INTERFACE_SYNC_ERROR_AUTH" : "Authentication failed. Check username and password or Pro account status.",
	"INTERFACE_SYNC_ERROR_INTERNET" : "Error: Cannot establish an Internet connection.",
	"INTERFACE_SYNC_ERROR_NO_CONNECT" : "Error: Could not connect to {RTM_SHORT}.",
	"INTERFACE_SYNC_ERROR_TERMINATED" : "Synchronization terminated.",
	"INTERFACE_SYNC_ERROR_LOG" : "Sync not completed. See log for details.",
	"INTERFACE_SYNC_MSG_INTERRUPT" : "Do you really want to interrupt the synchronization?",
	"INTERFACE_SYNC_ABOUT" : "{MILKSYNC} for Windows Mobile",
	"INTERFACE_SYNC_ABOUT_MILKSYNC" : "About {MILKSYNC}",
	"INTERFACE_SYNC_SETTINGS_DIRECTION" : "Sync Direction:",
	"INTERFACE_SYNC_DIRECTION_TWO" : "Two-way",
	"INTERFACE_SYNC_DIRECTION_RTM_TO_DEVICE" : "{RTM_SHORT} to device only",
	"INTERFACE_SYNC_DIRECTION_DEVICE_TO_RTM" : "Device to {RTM_SHORT} only",
	"INTERFACE_SYNC_TITLE_SCHEDULER" : "Scheduler:",
	"INTERFACE_SYNC_SCHED_MANUAL" : "Manual Sync",
	"INTERFACE_SYNC_SCHED_5MIN" : "Sync every 5 minutes",
	"INTERFACE_SYNC_SCHED_10MIN" : "Sync every 10 minutes",
	"INTERFACE_SYNC_SCHED_15MIN" : "Sync every 15 minutes",
	"INTERFACE_SYNC_SCHED_30MIN" : "Sync every 30 minutes",
	"INTERFACE_SYNC_SCHED_1HOUR" : "Sync every hour",
	"INTERFACE_SYNC_SCHED_2HOURS" : "Sync every 2 hours",
	"INTERFACE_SYNC_SCHED_4HOURS" : "Sync every 4 hours",
	"INTERFACE_SYNC_SCHED_DAILY" : "Sync once a day",
	"INTERFACE_SYNC_TITLE_CRADLE" : "Cradle:",
	"INTERFACE_SYNC_CRADLE_MSG" : "Sync on PC connection",
	"INTERFACE_SYNC_MSG_RESTORE_WARN" : "If you continue, all tasks will be {START_BOLD}deleted{END_BOLD} from your device and {START_BOLD}replaced{END_BOLD} with the tasks in your {RTM} account.",
	"INTERFACE_SYNC_LIST_INCLUDED" : "This list is included in sync. {START_LINK}Remove?{END_LINK}",
	"INTERFACE_SYNC_LIST_NOT_INCLUDED" : "This list is {START_ITALIC}not{END_ITALIC} included in sync. {START_LINK}Add?{END_LINK}",
	"INTERFACE_SYNC_MSG_PREFS" : "Set your preferences for {START_LINK}{MILKSYNC}{END_LINK}, a way to synchronize your {RTM} tasks with other software and devices.",
	"INTERFACE_SYNC_CURRENTLY_AVAILABLE" : "{START_BOLD}{MILKSYNC}{END_BOLD} is currently available for: {PRODUCT_NAMES}.",
	"INTERFACE_SYNC_GET_IT_NOW" : "{START_LINK}Get it now{END_LINK}.",
	"INTERFACE_SYNC_NO_PRO" : "{START_LINK}{MILKSYNC}{END_LINK} is a super cool way to synchronize your {RTM} tasks with other software and devices. It's currently available for: {PRODUCT_NAMES}.",
	"INTERFACE_SYNC_NEED_PRO" : "You'll need a {START_BOLD}Pro account{END_BOLD} to use {MILKSYNC}. {START_LINK}Upgrade now?{END_LINK}",
	"INTERFACE_SYNC_WHEN_SYNCING" : "When synchronizing my tasks...",
	"INTERFACE_SYNC_WHEN_ALL" : "Synchronize all lists",
	"INTERFACE_SYNC_WHEN_SOME" : "Synchronize only lists I've specified on the {START_LINK}Lists{END_LINK} screen",
	"INTERFACE_SYNC_STATUS_NOW_INCLUDED" : "List \"{LIST_NAME}\" will now be included in sync.",
	"INTERFACE_SYNC_STATUS_NOT_INCLUDED" : "List \"{LIST_NAME}\" will no longer be included in sync.",
	"INTERFACE_TAGS_ALREADY_EXISTS" : "You already have a tag named \"{TAG_NAME}\". Please choose another name.",
	"INTERFACE_PRIVATE_URL_RESET_STATUS" : "Private URLs have been reset.",
	"INTERFACE_PRIVATE_URL_ON" : "Private addresses are now on.",
	"INTERFACE_PRIVATE_URL_OFF" : "Private addresses have been turned off.",
	"INTERFACE_TAGS_MUST_SELECT_TWO" : "You must select two or more tags to merge.",
	"INTERFACE_TAGS_SELECTOR_MERGE" : "Merge Tags...",
	"INTERFACE_TAGS_SELECTOR_DELETE" : "Delete Tag",
	"INTERFACE_TAGS_STATUS_RENAME" : "Tag \"{TAG_NAME}\" renamed to \"{OTHER_TAG_NAME}\".",
	"INTERFACE_TAGS_STATUS_MERGE_ONE" : "Tag \"{TAG_NAME}\" merged into tag \"{OTHER_TAG_NAME}\".",
	"INTERFACE_TAGS_STATUS_MERGE_NUM" : "{TAG_NUM} tags merged into tag \"{OTHER_TAG_NAME}\".",
	"INTERFACE_TAGS_STATUS_DELETED_ONE" : "Tag \"{TAG_NAME}\" deleted.",
	"INTERFACE_TAGS_STATUS_DELETED_NUM" : "{TAG_NUM} tags deleted.",
	"INTERFACE_TAGS_SELECTED_ONE" : "1 tag selected.",
	"INTERFACE_TAGS_SELECTED_NUM" : "{NUM} tags selected.",
	"INTERFACE_TAGS_ZERO" : "0 tags",
	"INTERFACE_TAGS_ONE" : "1 tag",
	"INTERFACE_TAGS_NUM" : "{NUM} tags",
	"INTERFACE_DIALOG_REPEAT_TITLE_ONE" : "Delete Repeating Task",
	"INTERFACE_DIALOG_REPEAT_TITLE_NUM" : "Delete Repeating Tasks",
	"INTERFACE_DIALOG_REPEAT_BUTTON_CONTINUE" : "Continue repeating",
	"INTERFACE_DIALOG_REPEAT_BUTTON_STOP" : "Stop repeating",
	"INTERFACE_DIALOG_REPEAT_TEXT_ONE" : "You are deleting a task that repeats. Should this task continue repeating in the future, or should it stop repeating?",
	"INTERFACE_DIALOG_REPEAT_TEXT_NUM" : "You are deleting tasks that repeat. Should these tasks continue repeating in the future, or should they stop repeating?",
	"INTERFACE_DIALOG_MERGE_TITLE" : "Merge Tags",
	"INTERFACE_DIALOG_MERGE_TEXT_ONE" : "You are merging two or more tags into a single tag.",
	"INTERFACE_DIALOG_MERGE_TAG_NAME_LABEL" : "Tag name:",
	"INTERFACE_TAGS_NO_TAGS" : "You have no tags. You should create some!",
	"INTERFACE_SEARCH_ESTIMATE_IS" : "is",
	"INTERFACE_SEARCH_ESTIMATE_GREATER" : "is greater than",
	"INTERFACE_SEARCH_ESTIMATE_LESS" : "is less than",
	"INTERFACE_TAGS_HELP_MANAGE" : "Manage your tags.",
	"INTERFACE_TAGS_HELP_REMOVING" : "{START_ITALIC}Note:{END_ITALIC} Removing a tag will not delete the tasks with that tag.",
	"INTERFACE_SEARCH_ESTIMATE_EXAMPLE" : "e.g. 20 min",
	"INTERFACE_SEARCH_MORE" : "More {START_LINK}advanced searching{END_LINK} available.",
	"INTERFACE_SETTINGS_SHOW_TAGS" : "Show tags within list on the Tasks screen",
	"INTERFACE_SETTINGS_LEARN_MORE" : "Learn more",
	"INTERFACE_SETTINGS_PRIVATE_LABEL" : "Private Addresses",
	"INTERFACE_SETTINGS_PRIVATE_RESET" : "Reset Private URLs",
	"INTERFACE_SHARE_CANNOT_BE_SHARED" : "This list cannot be shared.",
	"INTERFACE_SETTINGS_TAGS_LEFT" : "Show tags on the left",
	"INTERFACE_SETTINGS_TAGS_RIGHT" : "Show tags on the right",
	"INTERFACE_SETTINGS_TAGS_NONE" : "Don't show tags in list",
	"INTERFACE_TASKS_SELECTED_ONE_TASK_MULTIEDIT_NEW" : "1 task selected {START_BOLD}(multi-edit){END_BOLD}.",
	"INTERFACE_TASKS_SELECTED_NUM_TASKS_MULTIEDIT_NEW" : "{NUM} tasks selected {START_BOLD}(multi-edit){END_BOLD}.",
	"INTERFACE_SMART_ADD_NAME" : "Smart Add",
	"INTERFACE_SMART_ADD_LABEL" : "Add a new task",
	"INTERFACE_SMART_ADD_TASK_ADDED" : "Task \"{TASK_NAME}\" added.",
	"INTERFACE_SMART_ADD_TASK_ADDED_WITH_DUE" : "Task \"{TASK_NAME}\" added. Due {DUE_DATE}.",
	"INTERFACE_SMART_ADD_SHORTCUTS" : "Smart Add Shortcuts",
	"INTERFACE_SMART_ADD_LISTS_AND_TAGS" : "Lists and Tags",
	"INTERFACE_SMART_ADD_LEARN_MORE" : "Learn more about Smart Add",
	"HOMEPAGE_TOP_NAV_ABOUT" : "About",
	"HOMEPAGE_TOP_NAV_SIGNUP" : "Signup",
	"HOMEPAGE_TOP_NAV_LOGIN" : "Login",
	"MOBILE_HEADING_TASKS" : "{FIRST_NAME} Tasks",
	"MOBILE_DETAIL_DUE" : "Due:",
	"MOBILE_DETAIL_PRIORITY" : "Priority:",
	"MOBILE_DETAIL_LIST" : "List:",
	"MOBILE_DETAIL_TAGS" : "Tags:",
	"MOBILE_DETAIL_REPEAT" : "Repeat:",
	"MOBILE_DETAIL_ESTIMATE" : "Time estimate:",
	"MOBILE_DETAIL_POSTPONED" : "Postponed:",
	"MOBILE_DETAIL_URL" : "URL:",
	"MOBILE_DETAIL_NOTES" : "Notes:",
	"MOBILE_DETAIL_LOCATION" : "Location:",
	"MOBILE_HEADING_THIS_WEEK" : "This Week",
	"HOMEPAGE_NEW" : "New!"
};